%% Author: php
%% Created:
%% Description: TODO: Add description to guild_party_packet
-module(guild_party_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_GUILD_PARTY_CS_LIST) ->
	?MSG_FORMAT_GUILD_PARTY_CS_LIST;
packet_format(?MSG_ID_GUILD_PARTY_SC_LIST) ->
	?MSG_FORMAT_GUILD_PARTY_SC_LIST;
packet_format(?MSG_ID_GUILD_PARTY_CS_PASSAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_PASSAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_SC_PASSAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PASSAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_CS_REFUSEAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_REFUSEAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_SC_REFUSEAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_REFUSEAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_CS_CREATEGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_CREATEGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_CREATEGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_CREATEGUILD;
packet_format(?MSG_ID_GUILD_PARTY_CS_DONATECOIN) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DONATECOIN;
packet_format(?MSG_ID_GUILD_PARTY_SC_DONATECOIN) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DONATECOIN;
packet_format(?MSG_ID_GUILD_PARTY_CS_JOINGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_JOINGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_JOINGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_JOINGUILD;
packet_format(?MSG_ID_GUILD_PARTY_CS_DISBANDGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DISBANDGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_DISBANDGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DISBANDGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_STATE_CHANGE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_STATE_CHANGE;
packet_format(?MSG_ID_GUILD_PARTY_CS_QUITGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_QUITGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_QUITGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_QUITGUILD;
packet_format(?MSG_ID_GUILD_PARTY_CS_CANCELAPLLY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_CANCELAPLLY;
packet_format(?MSG_ID_GUILD_PARTY_SC_CANCELAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_CANCELAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_CS_LEARNMAGIC) ->
	?MSG_FORMAT_GUILD_PARTY_CS_LEARNMAGIC;
packet_format(?MSG_ID_GUILD_PARTY_SC_LEARNMAGIC) ->
	?MSG_FORMAT_GUILD_PARTY_SC_LEARNMAGIC;
packet_format(?MSG_ID_GUILD_PARTY_CS_DEFAULTSKILL) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DEFAULTSKILL;
packet_format(?MSG_ID_GUILD_PARTY_SC_DEFAULTSKILL) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DEFAULTSKILL;
packet_format(?MSG_ID_GUILD_PARTY_CS_GUILDINFO) ->
	?MSG_FORMAT_GUILD_PARTY_CS_GUILDINFO;
packet_format(?MSG_ID_GUILD_PARTY_SC_GUILDINFO) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GUILDINFO;
packet_format(?MSG_ID_GUILD_PARTY_CS_GUILDMEM) ->
	?MSG_FORMAT_GUILD_PARTY_CS_GUILDMEM;
packet_format(?MSG_ID_GUILD_PARTY_SC_GUILDMEM) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GUILDMEM;
packet_format(?MSG_ID_GUILD_PARTY_CS_SKILLLIST) ->
	?MSG_FORMAT_GUILD_PARTY_CS_SKILLLIST;
packet_format(?MSG_ID_GUILD_PARTY_SC_SKILLLIST) ->
	?MSG_FORMAT_GUILD_PARTY_SC_SKILLLIST;
packet_format(?MSG_ID_GUILD_PARTY_CS_MAGICLIST) ->
	?MSG_FORMAT_GUILD_PARTY_CS_MAGICLIST;
packet_format(?MSG_ID_GUILD_PARTY_SC_MAGICLIST) ->
	?MSG_FORMAT_GUILD_PARTY_SC_MAGICLIST;
packet_format(?MSG_ID_GUILD_PARTY_CS_TRESUARE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_TRESUARE;
packet_format(?MSG_ID_GUILD_PARTY_SC_TREASURE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_TREASURE;
packet_format(?MSG_ID_GUILD_PARTY_CS_APPLYLIST) ->
	?MSG_FORMAT_GUILD_PARTY_CS_APPLYLIST;
packet_format(?MSG_ID_GUILD_PARTY_SC_APPLYLIST) ->
	?MSG_FORMAT_GUILD_PARTY_SC_APPLYLIST;
packet_format(?MSG_ID_GUILD_PARTY_CS_KICKOUT) ->
	?MSG_FORMAT_GUILD_PARTY_CS_KICKOUT;
packet_format(?MSG_ID_GUILD_PARTY_SC_KICKOUT) ->
	?MSG_FORMAT_GUILD_PARTY_SC_KICKOUT;
packet_format(?MSG_ID_GUILD_PARTY_CS_CHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_CS_CHIEF;
packet_format(?MSG_ID_GUILD_PARTY_SC_CHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_SC_CHIEF;
packet_format(?MSG_ID_GUILD_PARTY_CS_VICECHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_CS_VICECHIEF;
packet_format(?MSG_ID_GUILD_PARTY_SC_VICECHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_SC_VICECHIEF;
packet_format(?MSG_ID_GUILD_PARTY_CS_AUTO) ->
	?MSG_FORMAT_GUILD_PARTY_CS_AUTO;
packet_format(?MSG_ID_GUILD_PARTY_SC_AUTO) ->
	?MSG_FORMAT_GUILD_PARTY_SC_AUTO;
packet_format(?MSG_ID_GUILD_PARTY_CS_REMOVEDUTY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_REMOVEDUTY;
packet_format(?MSG_ID_GUILD_PARTY_SC_REMOVEDUTY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_REMOVEDUTY;
packet_format(?MSG_ID_GUILD_PARTY_CS_IMPEACHCHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_CS_IMPEACHCHIEF;
packet_format(?MSG_ID_GUILD_PARTY_SC_IMPEACHCHIEF) ->
	?MSG_FORMAT_GUILD_PARTY_SC_IMPEACHCHIEF;
packet_format(?MSG_ID_GUILD_PARTY_CS_MODIFYMESSAGE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_MODIFYMESSAGE;
packet_format(?MSG_ID_GUILD_PARTY_SC_MODIFYMESSAGE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_MODIFYMESSAGE;
packet_format(?MSG_ID_GUILD_PARTY_CS_GUILDLOG) ->
	?MSG_FORMAT_GUILD_PARTY_CS_GUILDLOG;
packet_format(?MSG_ID_GUILD_PARTY_SC_GUILDLOG) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GUILDLOG;
packet_format(?MSG_ID_GUILD_PARTY_CS_WELFEAR) ->
	?MSG_FORMAT_GUILD_PARTY_CS_WELFEAR;
packet_format(?MSG_ID_GUILD_PARTY_SC_WELFEAR) ->
	?MSG_FORMAT_GUILD_PARTY_SC_WELFEAR;
packet_format(?MSG_ID_GUILD_PARTY_CS_BUYTRESURE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_BUYTRESURE;
packet_format(?MSG_ID_GUILD_PARTY_SC_BUYTRESURE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_BUYTRESURE;
packet_format(?MSG_ID_GUILD_PARTY_CS_DEALAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DEALAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_SC_DEALAPPLY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DEALAPPLY;
packet_format(?MSG_ID_GUILD_PARTY_CS_MODIFYANNOU) ->
	?MSG_FORMAT_GUILD_PARTY_CS_MODIFYANNOU;
packet_format(?MSG_ID_GUILD_PARTY_SC_MODIFYANNOU) ->
	?MSG_FORMAT_GUILD_PARTY_SC_MODIFYANNOU;
packet_format(?MSG_ID_GUILD_PARTY_CS_INVITEGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_INVITEGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_INVITEGUILD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_INVITEGUILD;
packet_format(?MSG_ID_GUILD_PARTY_SC_INVITEED) ->
	?MSG_FORMAT_GUILD_PARTY_SC_INVITEED;
packet_format(?MSG_ID_GUILD_PARTY_SC_INVITE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_INVITE;
packet_format(?MSG_ID_GUILD_PARTY_CS_END_TIME) ->
	?MSG_FORMAT_GUILD_PARTY_CS_END_TIME;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTYINFO) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTYINFO;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTYMEM) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTYMEM;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTYPARTNER) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTYPARTNER;
packet_format(?MSG_ID_GUILD_PARTY_PLAY_FIREWORKS) ->
	?MSG_FORMAT_GUILD_PARTY_PLAY_FIREWORKS;
packet_format(?MSG_ID_GUILD_PARTY_CS_ENTER_PARTY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_ENTER_PARTY;
packet_format(?MSG_ID_GUILD_PARTY_SC_ENTER_PARTY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ENTER_PARTY;
packet_format(?MSG_ID_GUILD_PARTY_CS_LEAVE_PARTY) ->
	?MSG_FORMAT_GUILD_PARTY_CS_LEAVE_PARTY;
packet_format(?MSG_ID_GUILD_PARTY_SC_LEAVE_PARTY) ->
	?MSG_FORMAT_GUILD_PARTY_SC_LEAVE_PARTY;
packet_format(?MSG_ID_GUILD_PARTY_SC_GUESS_INFO) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GUESS_INFO;
packet_format(?MSG_ID_GUILD_PARTY_CS_INVITE_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_CS_INVITE_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_SC_INVITE_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_SC_INVITE_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_CS_AGREE_REFUSE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_AGREE_REFUSE;
packet_format(?MSG_ID_GUILD_PARTY_CS_OUT_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_CS_OUT_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_SC_OUT_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_SC_OUT_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_SC_OUT_RES) ->
	?MSG_FORMAT_GUILD_PARTY_SC_OUT_RES;
packet_format(?MSG_ID_GUILD_PARTY_SC_RES_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_SC_RES_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_CS_EXIT_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_CS_EXIT_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_SC_EXIT_GUESS) ->
	?MSG_FORMAT_GUILD_PARTY_SC_EXIT_GUESS;
packet_format(?MSG_ID_GUILD_PARTY_SC_ROCK_DATA) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ROCK_DATA;
packet_format(?MSG_ID_GUILD_PARTY_CS_INVITE_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_CS_INVITE_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_SC_INVITE_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_SC_INVITE_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_CS_ROCK_AGREE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_ROCK_AGREE;
packet_format(?MSG_ID_GUILD_PARTY_SC_ROCK_START) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ROCK_START;
packet_format(?MSG_ID_GUILD_PARTY_CS_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_CS_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_SC_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_ROCK_RESULT) ->
	?MSG_FORMAT_GUILD_PARTY_ROCK_RESULT;
packet_format(?MSG_ID_GUILD_PARTY_SC_ROCK_RES) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ROCK_RES;
packet_format(?MSG_ID_GUILD_PARTY_CS_EXIT_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_CS_EXIT_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_SC_EXIT_ROCK) ->
	?MSG_FORMAT_GUILD_PARTY_SC_EXIT_ROCK;
packet_format(?MSG_ID_GUILD_PARTY_CS_DESK_TIMES) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DESK_TIMES;
packet_format(?MSG_ID_GUILD_PARTY_SC_DESK_TIMES) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DESK_TIMES;
packet_format(?MSG_ID_GUILD_PARTY_CS_GET_DESKREWARD) ->
	?MSG_FORMAT_GUILD_PARTY_CS_GET_DESKREWARD;
packet_format(?MSG_ID_GUILD_PARTY_SC_GET_DESKREWARD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GET_DESKREWARD;
packet_format(?MSG_ID_GUILD_PARTY_CS_RESET_TIMES) ->
	?MSG_FORMAT_GUILD_PARTY_CS_RESET_TIMES;
packet_format(?MSG_ID_GUILD_PARTY_SC_RESET_TIMES) ->
	?MSG_FORMAT_GUILD_PARTY_SC_RESET_TIMES;
packet_format(?MSG_ID_GUILD_PARTY_MEAT) ->
	?MSG_FORMAT_GUILD_PARTY_MEAT;
packet_format(?MSG_ID_GUILD_PARTY_PARTY_NORMAL_STATE) ->
	?MSG_FORMAT_GUILD_PARTY_PARTY_NORMAL_STATE;
packet_format(?MSG_ID_GUILD_PARTY_SC_ROCK_EXIT) ->
	?MSG_FORMAT_GUILD_PARTY_SC_ROCK_EXIT;
packet_format(?MSG_ID_GUILD_PARTY_SC_END_REWARD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_END_REWARD;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_EXP) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_EXP;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_SP) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_SP;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_GOLD) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_GOLD;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_EXPERIENCE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_EXPERIENCE;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_RANK) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_RANK;
packet_format(?MSG_ID_GUILD_PARTY_SC_PARTY_QUIT_NOTICE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_PARTY_QUIT_NOTICE;
packet_format(?MSG_ID_GUILD_PARTY_CS_PARTY_END_QUIT) ->
	?MSG_FORMAT_GUILD_PARTY_CS_PARTY_END_QUIT;
packet_format(?MSG_ID_GUILD_PARTY_CTN_REQUEST) ->
	?MSG_FORMAT_GUILD_PARTY_CTN_REQUEST;
packet_format(?MSG_ID_GUILD_PARTY_CS_DISTRIBUTE) ->
	?MSG_FORMAT_GUILD_PARTY_CS_DISTRIBUTE;
packet_format(?MSG_ID_GUILD_PARTY_SC_DISTRIBUTE) ->
	?MSG_FORMAT_GUILD_PARTY_SC_DISTRIBUTE;
packet_format(?MSG_ID_GUILD_PARTY_CS_GUILD_MEMINFO) ->
	?MSG_FORMAT_GUILD_PARTY_CS_GUILD_MEMINFO;
packet_format(?MSG_ID_GUILD_PARTY_SC_GUILD_MEMINFO) ->
	?MSG_FORMAT_GUILD_PARTY_SC_GUILD_MEMINFO;
packet_format(?MSG_ID_GUILD_PARTY_GUILD_BAG_EMPTY) ->
	?MSG_FORMAT_GUILD_PARTY_GUILD_BAG_EMPTY;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
