%% Author: php
%% Created:
%% Description: TODO: Add description to copy_single_packet
-module(copy_single_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_COPY_SINGLE_CS_ENTER_COPY) ->
	?MSG_FORMAT_COPY_SINGLE_CS_ENTER_COPY;
packet_format(?MSG_ID_COPY_SINGLE_SC_MONSTER_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_SC_MONSTER_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_BATTLE_OK) ->
	?MSG_FORMAT_COPY_SINGLE_SC_BATTLE_OK;
packet_format(?MSG_ID_COPY_SINGLE_CS_EXIT_COPY) ->
	?MSG_FORMAT_COPY_SINGLE_CS_EXIT_COPY;
packet_format(?MSG_ID_COPY_SINGLE_CS_COPY_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_CS_COPY_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_COPY_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_SC_COPY_INFO;
packet_format(?MSG_ID_COPY_SINGLE_CS_AGAIN) ->
	?MSG_FORMAT_COPY_SINGLE_CS_AGAIN;
packet_format(?MSG_ID_COPY_SINGLE_SC_COPY_END) ->
	?MSG_FORMAT_COPY_SINGLE_SC_COPY_END;
packet_format(?MSG_ID_COPY_SINGLE_SC_UPDATE_COPY) ->
	?MSG_FORMAT_COPY_SINGLE_SC_UPDATE_COPY;
packet_format(?MSG_ID_COPY_SINGLE_CS_RAID) ->
	?MSG_FORMAT_COPY_SINGLE_CS_RAID;
packet_format(?MSG_ID_COPY_SINGLE_SC_PROCCESS_UPDATE) ->
	?MSG_FORMAT_COPY_SINGLE_SC_PROCCESS_UPDATE;
packet_format(?MSG_ID_COPY_SINGLE_CS_RAID_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_CS_RAID_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_RAID_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_SC_RAID_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_RAID_A_WAVE) ->
	?MSG_FORMAT_COPY_SINGLE_SC_RAID_A_WAVE;
packet_format(?MSG_ID_COPY_SINGLE_CS_STOP) ->
	?MSG_FORMAT_COPY_SINGLE_CS_STOP;
packet_format(?MSG_ID_COPY_SINGLE_CS_QUICK) ->
	?MSG_FORMAT_COPY_SINGLE_CS_QUICK;
packet_format(?MSG_ID_COPY_SINGLE_SC_QUICK_OK) ->
	?MSG_FORMAT_COPY_SINGLE_SC_QUICK_OK;
packet_format(?MSG_ID_COPY_SINGLE_CS_BATTLE) ->
	?MSG_FORMAT_COPY_SINGLE_CS_BATTLE;
packet_format(?MSG_ID_COPY_SINGLE_IS_EMPTY_5) ->
	?MSG_FORMAT_COPY_SINGLE_IS_EMPTY_5;
packet_format(?MSG_ID_COPY_SINGLE_SC_EMPTY) ->
	?MSG_FORMAT_COPY_SINGLE_SC_EMPTY;
packet_format(?MSG_ID_COPY_SINGLE_CS_VIP_REQ) ->
	?MSG_FORMAT_COPY_SINGLE_CS_VIP_REQ;
packet_format(?MSG_ID_COPY_SINGLE_SC_VIP_REWARD) ->
	?MSG_FORMAT_COPY_SINGLE_SC_VIP_REWARD;
packet_format(?MSG_ID_COPY_SINGLE_CS_RESET_ELITE) ->
	?MSG_FORMAT_COPY_SINGLE_CS_RESET_ELITE;
packet_format(?MSG_ID_COPY_SINGLE_SC_RESET_LIST) ->
	?MSG_FORMAT_COPY_SINGLE_SC_RESET_LIST;
packet_format(?MSG_ID_COPY_SINGLE_SC_RESET) ->
	?MSG_FORMAT_COPY_SINGLE_SC_RESET;
packet_format(?MSG_ID_COPY_SINGLE_SC_NOTICE_ELITE_RESET) ->
	?MSG_FORMAT_COPY_SINGLE_SC_NOTICE_ELITE_RESET;
packet_format(?MSG_ID_COPY_SINGLE_CS_ELITE_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_CS_ELITE_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_ELITE_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_SC_ELITE_INFO;
packet_format(?MSG_ID_COPY_SINGLE_SC_ELITE_RESULT) ->
	?MSG_FORMAT_COPY_SINGLE_SC_ELITE_RESULT;
packet_format(?MSG_ID_COPY_SINGLE_CS_START_ELITE) ->
	?MSG_FORMAT_COPY_SINGLE_CS_START_ELITE;
packet_format(?MSG_ID_COPY_SINGLE_SC_START_ELITE) ->
	?MSG_FORMAT_COPY_SINGLE_SC_START_ELITE;
packet_format(?MSG_ID_COPY_SINGLE_SC_COPY_ALL_INFO) ->
	?MSG_FORMAT_COPY_SINGLE_SC_COPY_ALL_INFO;
packet_format(?MSG_ID_COPY_SINGLE_CS_AUTO_TURNCARD) ->
	?MSG_FORMAT_COPY_SINGLE_CS_AUTO_TURNCARD;
packet_format(?MSG_ID_COPY_SINGLE_SC_AUTOCARD) ->
	?MSG_FORMAT_COPY_SINGLE_SC_AUTOCARD;
packet_format(?MSG_ID_COPY_SINGLE_AUTO_TURNCARD_REWARD) ->
	?MSG_FORMAT_COPY_SINGLE_AUTO_TURNCARD_REWARD;
packet_format(?MSG_ID_COPY_SINGLE_CS_REPORT_LIST) ->
	?MSG_FORMAT_COPY_SINGLE_CS_REPORT_LIST;
packet_format(?MSG_ID_COPY_SINGLE_SC_REPORT_LIST) ->
	?MSG_FORMAT_COPY_SINGLE_SC_REPORT_LIST;
packet_format(?MSG_ID_COPY_SINGLE_CS_STEP_OK) ->
	?MSG_FORMAT_COPY_SINGLE_CS_STEP_OK;
packet_format(?MSG_ID_COPY_SINGLE_SC_EQUIP) ->
	?MSG_FORMAT_COPY_SINGLE_SC_EQUIP;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
