%% Author: php
%% Created:
%% Description: TODO: Add description to new_serv_packet
-module(new_serv_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_NEW_SERV_CS_ACHIEVE) ->
	?MSG_FORMAT_NEW_SERV_CS_ACHIEVE;
packet_format(?MSG_ID_NEW_SERV_SC_ACHIEVE) ->
	?MSG_FORMAT_NEW_SERV_SC_ACHIEVE;
packet_format(?MSG_ID_NEW_SERV_CS_ACHIEVE_RECEIVE) ->
	?MSG_FORMAT_NEW_SERV_CS_ACHIEVE_RECEIVE;
packet_format(?MSG_ID_NEW_SERV_SC_ACHIEVE_RECEIVE) ->
	?MSG_FORMAT_NEW_SERV_SC_ACHIEVE_RECEIVE;
packet_format(?MSG_ID_NEW_SERV_CS_RANK) ->
	?MSG_FORMAT_NEW_SERV_CS_RANK;
packet_format(?MSG_ID_NEW_SERV_SC_RANK) ->
	?MSG_FORMAT_NEW_SERV_SC_RANK;
packet_format(?MSG_ID_NEW_SERV_CS_STORAGE_INFO) ->
	?MSG_FORMAT_NEW_SERV_CS_STORAGE_INFO;
packet_format(?MSG_ID_NEW_SERV_SC_STORAGE_INFO) ->
	?MSG_FORMAT_NEW_SERV_SC_STORAGE_INFO;
packet_format(?MSG_ID_NEW_SERV_CS_STORAGE) ->
	?MSG_FORMAT_NEW_SERV_CS_STORAGE;
packet_format(?MSG_ID_NEW_SERV_CS_DRAW_STORAGE) ->
	?MSG_FORMAT_NEW_SERV_CS_DRAW_STORAGE;
packet_format(?MSG_ID_NEW_SERV_CS_END_TIME) ->
	?MSG_FORMAT_NEW_SERV_CS_END_TIME;
packet_format(?MSG_ID_NEW_SERV_SC_END_TIME) ->
	?MSG_FORMAT_NEW_SERV_SC_END_TIME;
packet_format(?MSG_ID_NEW_SERV_CS_HERO_RANK) ->
	?MSG_FORMAT_NEW_SERV_CS_HERO_RANK;
packet_format(?MSG_ID_NEW_SERV_SC_HERO_RANK) ->
	?MSG_FORMAT_NEW_SERV_SC_HERO_RANK;
packet_format(?MSG_ID_NEW_SERV_CS_DEPOSIT_REWARD) ->
	?MSG_FORMAT_NEW_SERV_CS_DEPOSIT_REWARD;
packet_format(?MSG_ID_NEW_SERV_SC_DEPOSIT_REWARD) ->
	?MSG_FORMAT_NEW_SERV_SC_DEPOSIT_REWARD;
packet_format(?MSG_ID_NEW_SERV_CS_HONOR_PLAYER_INFO) ->
	?MSG_FORMAT_NEW_SERV_CS_HONOR_PLAYER_INFO;
packet_format(?MSG_ID_NEW_SERV_SC_HONOR_PLAYER_INFO) ->
	?MSG_FORMAT_NEW_SERV_SC_HONOR_PLAYER_INFO;
packet_format(?MSG_ID_NEW_SERV_SC_TRAVELL_TIMES) ->
	?MSG_FORMAT_NEW_SERV_SC_TRAVELL_TIMES;
packet_format(?MSG_ID_NEW_SERV_CS_TURN) ->
	?MSG_FORMAT_NEW_SERV_CS_TURN;
packet_format(?MSG_ID_NEW_SERV_SC_TARGET) ->
	?MSG_FORMAT_NEW_SERV_SC_TARGET;
packet_format(?MSG_ID_NEW_SERV_CS_SEND) ->
	?MSG_FORMAT_NEW_SERV_CS_SEND;
packet_format(?MSG_ID_NEW_SERV_SC_REPLY) ->
	?MSG_FORMAT_NEW_SERV_SC_REPLY;
packet_format(?MSG_ID_NEW_SERV_CS_EXCHANGE_CASH) ->
	?MSG_FORMAT_NEW_SERV_CS_EXCHANGE_CASH;
packet_format(?MSG_ID_NEW_SERV_CS_EXCHANGE_GOODS) ->
	?MSG_FORMAT_NEW_SERV_CS_EXCHANGE_GOODS;
packet_format(?MSG_ID_NEW_SERV_CS_EXCHANGE_INFO) ->
	?MSG_FORMAT_NEW_SERV_CS_EXCHANGE_INFO;
packet_format(?MSG_ID_NEW_SERV_SC_EXCHANGE_INFO) ->
	?MSG_FORMAT_NEW_SERV_SC_EXCHANGE_INFO;
packet_format(?MSG_ID_NEW_SERV_SC_TOTAL_SHOW) ->
	?MSG_FORMAT_NEW_SERV_SC_TOTAL_SHOW;
packet_format(?MSG_ID_NEW_SERV_CS_TURN_GROUP_ID) ->
	?MSG_FORMAT_NEW_SERV_CS_TURN_GROUP_ID;
packet_format(?MSG_ID_NEW_SERV_SC_TURN_GROUP_ID) ->
	?MSG_FORMAT_NEW_SERV_SC_TURN_GROUP_ID;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
