%% Author: php
%% Created:
%% Description: TODO: Add description to practice_packet
-module(practice_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_PRACTICE_SINGLE_REQUEST) ->
	?MSG_FORMAT_PRACTICE_SINGLE_REQUEST;
packet_format(?MSG_ID_PRACTICE_SINGLE) ->
	?MSG_FORMAT_PRACTICE_SINGLE;
packet_format(?MSG_ID_PRACTICE_DOUBLE_REQUEST) ->
	?MSG_FORMAT_PRACTICE_DOUBLE_REQUEST;
packet_format(?MSG_ID_PRACTICE_DOUBLE_RECEIVE) ->
	?MSG_FORMAT_PRACTICE_DOUBLE_RECEIVE;
packet_format(?MSG_ID_PRACTICE_DOUBLE_REPLY) ->
	?MSG_FORMAT_PRACTICE_DOUBLE_REPLY;
packet_format(?MSG_ID_PRACTICE_DOUBLE) ->
	?MSG_FORMAT_PRACTICE_DOUBLE;
packet_format(?MSG_ID_PRACTICE_REWARD) ->
	?MSG_FORMAT_PRACTICE_REWARD;
packet_format(?MSG_ID_PRACTICE_CANCEL) ->
	?MSG_FORMAT_PRACTICE_CANCEL;
packet_format(?MSG_ID_PRACTICE_CANCEL_DATA) ->
	?MSG_FORMAT_PRACTICE_CANCEL_DATA;
packet_format(?MSG_ID_PRACTICE_VIP_OPTIONS) ->
	?MSG_FORMAT_PRACTICE_VIP_OPTIONS;
packet_format(?MSG_ID_PRACTICE_OPTIONS) ->
	?MSG_FORMAT_PRACTICE_OPTIONS;
packet_format(?MSG_ID_PRACTICE_OPTIONS_DATA) ->
	?MSG_FORMAT_PRACTICE_OPTIONS_DATA;
packet_format(?MSG_ID_PRACTICE_CS_LEAVE_EXP) ->
	?MSG_FORMAT_PRACTICE_CS_LEAVE_EXP;
packet_format(?MSG_ID_PRACTICE_SC_LEAVE_EXP) ->
	?MSG_FORMAT_PRACTICE_SC_LEAVE_EXP;
packet_format(?MSG_ID_PRACTICE_CS_DOUBLE_STATE) ->
	?MSG_FORMAT_PRACTICE_CS_DOUBLE_STATE;
packet_format(?MSG_ID_PRACTICE_CS_OFFLINE_SET) ->
	?MSG_FORMAT_PRACTICE_CS_OFFLINE_SET;
packet_format(?MSG_ID_PRACTICE_SC_OFFLINE_SET_RES) ->
	?MSG_FORMAT_PRACTICE_SC_OFFLINE_SET_RES;
packet_format(?MSG_ID_PRACTICE_CS_QUERY_OFFLINE_SET) ->
	?MSG_FORMAT_PRACTICE_CS_QUERY_OFFLINE_SET;
packet_format(?MSG_ID_PRACTICE_SC_OFFLINE_SET_REP) ->
	?MSG_FORMAT_PRACTICE_SC_OFFLINE_SET_REP;
packet_format(?MSG_ID_PRACTICE_CS_CANCEL_OFFLINE_SET) ->
	?MSG_FORMAT_PRACTICE_CS_CANCEL_OFFLINE_SET;
packet_format(?MSG_ID_PRACTICE_CS_GET_VALID_TIME) ->
	?MSG_FORMAT_PRACTICE_CS_GET_VALID_TIME;
packet_format(?MSG_ID_PRACTICE_SC_VALID_TIME) ->
	?MSG_FORMAT_PRACTICE_SC_VALID_TIME;
packet_format(?MSG_ID_PRACTICE_SC_OFFLINE_CLEAN) ->
	?MSG_FORMAT_PRACTICE_SC_OFFLINE_CLEAN;
packet_format(?MSG_ID_PRACTICE_CS_CLEAR_CD) ->
	?MSG_FORMAT_PRACTICE_CS_CLEAR_CD;
packet_format(?MSG_ID_PRACTICE_SC_TIME) ->
	?MSG_FORMAT_PRACTICE_SC_TIME;
packet_format(?MSG_ID_PRACTICE_SC_FINISH_TIME) ->
	?MSG_FORMAT_PRACTICE_SC_FINISH_TIME;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
