%% Author: php
%% Created: 
%% Description: TODO: Add description to gateway_dispatcher
-module(gateway_dispatcher).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([dispatch/1]).
%%
%% API Functions
%%
dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SYS ->
	{?MODULE_PACKET_SYS, ?MODULE_HANDLER_SYS};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PLAYER ->
	{?MODULE_PACKET_PLAYER, ?MODULE_HANDLER_PLAYER};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GOODS ->
	{?MODULE_PACKET_GOODS, ?MODULE_HANDLER_GOODS};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_BATTLE ->
	{?MODULE_PACKET_BATTLE, ?MODULE_HANDLER_BATTLE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PARTNER ->
	{?MODULE_PACKET_PARTNER, ?MODULE_HANDLER_PARTNER};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MAP ->
	{?MODULE_PACKET_MAP, ?MODULE_HANDLER_MAP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ACHIEVEMENT ->
	{?MODULE_PACKET_ACHIEVEMENT, ?MODULE_HANDLER_ACHIEVEMENT};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_HOME ->
	{?MODULE_PACKET_HOME, ?MODULE_HANDLER_HOME};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CHAT ->
	{?MODULE_PACKET_CHAT, ?MODULE_HANDLER_CHAT};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MAIL ->
	{?MODULE_PACKET_MAIL, ?MODULE_HANDLER_MAIL};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PET ->
	{?MODULE_PACKET_PET, ?MODULE_HANDLER_PET};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ABILITY ->
	{?MODULE_PACKET_ABILITY, ?MODULE_HANDLER_ABILITY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CAMP ->
	{?MODULE_PACKET_CAMP, ?MODULE_HANDLER_CAMP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_FURNACE ->
	{?MODULE_PACKET_FURNACE, ?MODULE_HANDLER_FURNACE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_COPY_SINGLE ->
	{?MODULE_PACKET_COPY_SINGLE, ?MODULE_HANDLER_COPY_SINGLE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_RELATIONSHIP ->
	{?MODULE_PACKET_RELATIONSHIP, ?MODULE_HANDLER_RELATIONSHIP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_RELATION ->
	{?MODULE_PACKET_RELATION, ?MODULE_HANDLER_RELATION};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_BLESS ->
	{?MODULE_PACKET_BLESS, ?MODULE_HANDLER_BLESS};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUILD_PARTY ->
	{?MODULE_PACKET_GUILD_PARTY, ?MODULE_HANDLER_GUILD_PARTY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUILD ->
	{?MODULE_PACKET_GUILD, ?MODULE_HANDLER_GUILD};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PRACTICE ->
	{?MODULE_PACKET_PRACTICE, ?MODULE_HANDLER_PRACTICE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MARKET ->
	{?MODULE_PACKET_MARKET, ?MODULE_HANDLER_MARKET};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MALL ->
	{?MODULE_PACKET_MALL, ?MODULE_HANDLER_MALL};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_TEAM2 ->
	{?MODULE_PACKET_TEAM2, ?MODULE_HANDLER_TEAM2};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GROUP ->
	{?MODULE_PACKET_GROUP, ?MODULE_HANDLER_GROUP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_TASK ->
	{?MODULE_PACKET_TASK, ?MODULE_HANDLER_TASK};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_RANK ->
	{?MODULE_PACKET_RANK, ?MODULE_HANDLER_RANK};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_RESOURCE ->
	{?MODULE_PACKET_RESOURCE, ?MODULE_HANDLER_RESOURCE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SINGLE_ARENA ->
	{?MODULE_PACKET_SINGLE_ARENA, ?MODULE_HANDLER_SINGLE_ARENA};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_LOTTERY ->
	{?MODULE_PACKET_LOTTERY, ?MODULE_HANDLER_LOTTERY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MIND ->
	{?MODULE_PACKET_MIND, ?MODULE_HANDLER_MIND};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MESSAGE ->
	{?MODULE_PACKET_MESSAGE, ?MODULE_HANDLER_MESSAGE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SKILL ->
	{?MODULE_PACKET_SKILL, ?MODULE_HANDLER_SKILL};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_HORSE ->
	{?MODULE_PACKET_HORSE, ?MODULE_HANDLER_HORSE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SHOP ->
	{?MODULE_PACKET_SHOP, ?MODULE_HANDLER_SHOP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SPRING ->
	{?MODULE_PACKET_SPRING, ?MODULE_HANDLER_SPRING};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GM ->
	{?MODULE_PACKET_GM, ?MODULE_HANDLER_GM};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_TOWER ->
	{?MODULE_PACKET_TOWER, ?MODULE_HANDLER_TOWER};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_COMMERCE ->
	{?MODULE_PACKET_COMMERCE, ?MODULE_HANDLER_COMMERCE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ACTIVE ->
	{?MODULE_PACKET_ACTIVE, ?MODULE_HANDLER_ACTIVE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_WELFARE ->
	{?MODULE_PACKET_WELFARE, ?MODULE_HANDLER_WELFARE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_COLLECT ->
	{?MODULE_PACKET_COLLECT, ?MODULE_HANDLER_COLLECT};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_BOSS ->
	{?MODULE_PACKET_BOSS, ?MODULE_HANDLER_BOSS};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_INVASION ->
	{?MODULE_PACKET_INVASION, ?MODULE_HANDLER_INVASION};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SCHEDULE ->
	{?MODULE_PACKET_SCHEDULE, ?MODULE_HANDLER_SCHEDULE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUIDE ->
	{?MODULE_PACKET_GUIDE, ?MODULE_HANDLER_GUIDE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUILD_SIEGE ->
	{?MODULE_PACKET_GUILD_SIEGE, ?MODULE_HANDLER_GUILD_SIEGE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_FACTION ->
	{?MODULE_PACKET_FACTION, ?MODULE_HANDLER_FACTION};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MCOPY ->
	{?MODULE_PACKET_MCOPY, ?MODULE_HANDLER_MCOPY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_AI ->
	{?MODULE_PACKET_AI, ?MODULE_HANDLER_AI};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ARENA_PVP ->
	{?MODULE_PACKET_ARENA_PVP, ?MODULE_HANDLER_ARENA_PVP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_WORLD ->
	{?MODULE_PACKET_WORLD, ?MODULE_HANDLER_WORLD};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PARTY ->
	{?MODULE_PACKET_PARTY, ?MODULE_HANDLER_PARTY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_NEW_SERV ->
	{?MODULE_PACKET_NEW_SERV, ?MODULE_HANDLER_NEW_SERV};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CAMP_PVP ->
	{?MODULE_PACKET_CAMP_PVP, ?MODULE_HANDLER_CAMP_PVP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_WEAPON ->
	{?MODULE_PACKET_WEAPON, ?MODULE_HANDLER_WEAPON};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUILD_PVP ->
	{?MODULE_PACKET_GUILD_PVP, ?MODULE_HANDLER_GUILD_PVP};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_A ->
	{?MODULE_PACKET_A, ?MODULE_HANDLER_A};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_SNOW ->
	{?MODULE_PACKET_SNOW, ?MODULE_HANDLER_SNOW};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CROSS ->
	{?MODULE_PACKET_CROSS, ?MODULE_HANDLER_CROSS};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_YUNYING_ACTIVITY ->
	{?MODULE_PACKET_YUNYING_ACTIVITY, ?MODULE_HANDLER_YUNYING_ACTIVITY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CROSS_ARENA ->
	{?MODULE_PACKET_CROSS_ARENA, ?MODULE_HANDLER_CROSS_ARENA};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ARCHERY ->
	{?MODULE_PACKET_ARCHERY, ?MODULE_HANDLER_ARCHERY};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_ENCROACH ->
	{?MODULE_PACKET_ENCROACH, ?MODULE_HANDLER_ENCROACH};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_LANTERN ->
	{?MODULE_PACKET_LANTERN, ?MODULE_HANDLER_LANTERN};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_CARD21 ->
	{?MODULE_PACKET_CARD21, ?MODULE_HANDLER_CARD21};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GUN_CASH ->
	{?MODULE_PACKET_GUN_CASH, ?MODULE_HANDLER_GUN_CASH};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_TEACH ->
	{?MODULE_PACKET_TEACH, ?MODULE_HANDLER_TEACH};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_MIXED_SERV ->
	{?MODULE_PACKET_MIXED_SERV, ?MODULE_HANDLER_MIXED_SERV};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_PARTNER_SOUL ->
	{?MODULE_PACKET_PARTNER_SOUL, ?MODULE_HANDLER_PARTNER_SOUL};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_GAMBLE ->
	{?MODULE_PACKET_GAMBLE, ?MODULE_HANDLER_GAMBLE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_KB_TREASURE ->
	{?MODULE_PACKET_KB_TREASURE, ?MODULE_HANDLER_KB_TREASURE};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_HUNDRED_SERV ->
	{?MODULE_PACKET_HUNDRED_SERV, ?MODULE_HANDLER_HUNDRED_SERV};

dispatch(MsgId) when MsgId =< ?MODULE_TAIL_LIMIT_MALL ->
	{?MODULE_PACKET_LIMIT_MALL, ?MODULE_HANDLER_LIMIT_MALL};

%% 默认处理
dispatch(MsgId)->
	?MSG_ERROR("MsgId:~p~n",[MsgId]),
	{?error, MsgId}.
