%% Author: php
%% Created:
%% Description: TODO: Add description to team2_packet
-module(team2_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_TEAM2_CS_CREAT) ->
	?MSG_FORMAT_TEAM2_CS_CREAT;
packet_format(?MSG_ID_TEAM2_CS_JOIN) ->
	?MSG_FORMAT_TEAM2_CS_JOIN;
packet_format(?MSG_ID_TEAM2_CS_REMOVE) ->
	?MSG_FORMAT_TEAM2_CS_REMOVE;
packet_format(?MSG_ID_TEAM2_CS_QUIT) ->
	?MSG_FORMAT_TEAM2_CS_QUIT;
packet_format(?MSG_ID_TEAM2_CS_CHANGE_LEADER) ->
	?MSG_FORMAT_TEAM2_CS_CHANGE_LEADER;
packet_format(?MSG_ID_TEAM2_CS_INVITE) ->
	?MSG_FORMAT_TEAM2_CS_INVITE;
packet_format(?MSG_ID_TEAM2_CS_REPLY) ->
	?MSG_FORMAT_TEAM2_CS_REPLY;
packet_format(?MSG_ID_TEAM2_CS_SET_MEMBER_STATE) ->
	?MSG_FORMAT_TEAM2_CS_SET_MEMBER_STATE;
packet_format(?MSG_ID_TEAM2_CS_SET_CAMP) ->
	?MSG_FORMAT_TEAM2_CS_SET_CAMP;
packet_format(?MSG_ID_TEAM2_CS_SET_CAMP_POS) ->
	?MSG_FORMAT_TEAM2_CS_SET_CAMP_POS;
packet_format(?MSG_ID_TEAM2_CS_AUTOJOIN) ->
	?MSG_FORMAT_TEAM2_CS_AUTOJOIN;
packet_format(?MSG_ID_TEAM2_CS_QUIT_HALL) ->
	?MSG_FORMAT_TEAM2_CS_QUIT_HALL;
packet_format(?MSG_ID_TEAM2_CS_QUICK_JOIN) ->
	?MSG_FORMAT_TEAM2_CS_QUICK_JOIN;
packet_format(?MSG_ID_TEAM2_CS_LOCK_UNLOCK) ->
	?MSG_FORMAT_TEAM2_CS_LOCK_UNLOCK;
packet_format(?MSG_ID_TEAM2_CS_CHANGE_COPY2) ->
	?MSG_FORMAT_TEAM2_CS_CHANGE_COPY2;
packet_format(?MSG_ID_TEAM2_AUTHOR_LIST) ->
	?MSG_FORMAT_TEAM2_AUTHOR_LIST;
packet_format(?MSG_ID_TEAM2_CS_INVITE_AUTHOR) ->
	?MSG_FORMAT_TEAM2_CS_INVITE_AUTHOR;
packet_format(?MSG_ID_TEAM2_CS_SET_AUTHOR_LIST) ->
	?MSG_FORMAT_TEAM2_CS_SET_AUTHOR_LIST;
packet_format(?MSG_ID_TEAM2_INVITE_AUTHOR) ->
	?MSG_FORMAT_TEAM2_INVITE_AUTHOR;
packet_format(?MSG_ID_TEAM2_GOLD_HIRE) ->
	?MSG_FORMAT_TEAM2_GOLD_HIRE;
packet_format(?MSG_ID_TEAM2_GOLD_HIRE_INVITE) ->
	?MSG_FORMAT_TEAM2_GOLD_HIRE_INVITE;
packet_format(?MSG_ID_TEAM2_CS_QUICK_JOIN_CROSS) ->
	?MSG_FORMAT_TEAM2_CS_QUICK_JOIN_CROSS;
packet_format(?MSG_ID_TEAM2_SC_ENTER_HALL) ->
	?MSG_FORMAT_TEAM2_SC_ENTER_HALL;
packet_format(?MSG_ID_TEAM2_SC_ENTER_HALL_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_ENTER_HALL_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_QUIT_HALL_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_QUIT_HALL_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_TEAM_INSERT_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_TEAM_INSERT_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_TEAM_DELETE_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_TEAM_DELETE_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_INVITE_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_INVITE_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_REMOVE_INVITE) ->
	?MSG_FORMAT_TEAM2_SC_REMOVE_INVITE;
packet_format(?MSG_ID_TEAM2_SC_QUIT_NOTICE) ->
	?MSG_FORMAT_TEAM2_SC_QUIT_NOTICE;
packet_format(?MSG_ID_TEAM2_SC_INFO) ->
	?MSG_FORMAT_TEAM2_SC_INFO;
packet_format(?MSG_ID_TEAM2_SC_QUIT_PLAY_TO) ->
	?MSG_FORMAT_TEAM2_SC_QUIT_PLAY_TO;
packet_format(?MSG_ID_TEAM2_SC_CHANGE_COPY2) ->
	?MSG_FORMAT_TEAM2_SC_CHANGE_COPY2;
packet_format(?MSG_ID_TEAM2_SC_AUTHOR_LIST) ->
	?MSG_FORMAT_TEAM2_SC_AUTHOR_LIST;
packet_format(?MSG_ID_TEAM2_SC_INVITE_AUTHOR_LIST) ->
	?MSG_FORMAT_TEAM2_SC_INVITE_AUTHOR_LIST;
packet_format(?MSG_ID_TEAM2_SC_GOLD_HIRE) ->
	?MSG_FORMAT_TEAM2_SC_GOLD_HIRE;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
