%% Author: php
%% Created:
%% Description: TODO: Add description to furnace_packet
-module(furnace_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_FURNACE_STREN_QUEUE) ->
	?MSG_FORMAT_FURNACE_STREN_QUEUE;
packet_format(?MSG_ID_FURNACE_OPEN_STREN_QUEUE) ->
	?MSG_FORMAT_FURNACE_OPEN_STREN_QUEUE;
packet_format(?MSG_ID_FURNACE_CLEAR_STREN_CD) ->
	?MSG_FORMAT_FURNACE_CLEAR_STREN_CD;
packet_format(?MSG_ID_FURNACE_STREN_QUEUE_RETURN) ->
	?MSG_FORMAT_FURNACE_STREN_QUEUE_RETURN;
packet_format(?MSG_ID_FURNACE_SC_CANCEL_STREN_QUEUE) ->
	?MSG_FORMAT_FURNACE_SC_CANCEL_STREN_QUEUE;
packet_format(?MSG_ID_FURNACE_GET_USER_STREN) ->
	?MSG_FORMAT_FURNACE_GET_USER_STREN;
packet_format(?MSG_ID_FURNACE_GET_USER_STREN_RETURN) ->
	?MSG_FORMAT_FURNACE_GET_USER_STREN_RETURN;
packet_format(?MSG_ID_FURNACE_STREN_PART) ->
	?MSG_FORMAT_FURNACE_STREN_PART;
packet_format(?MSG_ID_FURNACE_STREN_PART_RETURN) ->
	?MSG_FORMAT_FURNACE_STREN_PART_RETURN;
packet_format(?MSG_ID_FURNACE_EQUIP_FORGE) ->
	?MSG_FORMAT_FURNACE_EQUIP_FORGE;
packet_format(?MSG_ID_FURNACE_EQUIP_FORGE_RETURN) ->
	?MSG_FORMAT_FURNACE_EQUIP_FORGE_RETURN;
packet_format(?MSG_ID_FURNACE_CS_UPGRADE_MULTI) ->
	?MSG_FORMAT_FURNACE_CS_UPGRADE_MULTI;
packet_format(?MSG_ID_FURNACE_SC_UPGRADE_MULTI) ->
	?MSG_FORMAT_FURNACE_SC_UPGRADE_MULTI;
packet_format(?MSG_ID_FURNACE_PLUS_INHERIT) ->
	?MSG_FORMAT_FURNACE_PLUS_INHERIT;
packet_format(?MSG_ID_FURNACE_PLUS_INHERIT_RETURN) ->
	?MSG_FORMAT_FURNACE_PLUS_INHERIT_RETURN;
packet_format(?MSG_ID_FURNACE_EQUIP_PLUS) ->
	?MSG_FORMAT_FURNACE_EQUIP_PLUS;
packet_format(?MSG_ID_FURNACE_EQUIP_PLUS_RETURN) ->
	?MSG_FORMAT_FURNACE_EQUIP_PLUS_RETURN;
packet_format(?MSG_ID_FURNACE_PLUS_CONFIRM) ->
	?MSG_FORMAT_FURNACE_PLUS_CONFIRM;
packet_format(?MSG_ID_FURNACE_PLUS_CONFIRM_RETURN) ->
	?MSG_FORMAT_FURNACE_PLUS_CONFIRM_RETURN;
packet_format(?MSG_ID_FURNACE_SOUL_CONFIRM) ->
	?MSG_FORMAT_FURNACE_SOUL_CONFIRM;
packet_format(?MSG_ID_FURNACE_SOUL_CONFIRM_RETURN) ->
	?MSG_FORMAT_FURNACE_SOUL_CONFIRM_RETURN;
packet_format(?MSG_ID_FURNACE_GOODS_FORGE) ->
	?MSG_FORMAT_FURNACE_GOODS_FORGE;
packet_format(?MSG_ID_FURNACE_GOODS_FORGE_RETURN) ->
	?MSG_FORMAT_FURNACE_GOODS_FORGE_RETURN;
packet_format(?MSG_ID_FURNACE_STREN_VALUE_UPDATE) ->
	?MSG_FORMAT_FURNACE_STREN_VALUE_UPDATE;
packet_format(?MSG_ID_FURNACE_SC_STYLE) ->
	?MSG_FORMAT_FURNACE_SC_STYLE;
packet_format(?MSG_ID_FURNACE_CS_FASHION_FUSION) ->
	?MSG_FORMAT_FURNACE_CS_FASHION_FUSION;
packet_format(?MSG_ID_FURNACE_SC_FUSION_RETURN) ->
	?MSG_FORMAT_FURNACE_SC_FUSION_RETURN;
packet_format(?MSG_ID_FURNACE_CS_SAVE_FASHION) ->
	?MSG_FORMAT_FURNACE_CS_SAVE_FASHION;
packet_format(?MSG_ID_FURNACE_CS_EQUIP_STATES) ->
	?MSG_FORMAT_FURNACE_CS_EQUIP_STATES;
packet_format(?MSG_ID_FURNACE_SC_EQUIP_STATES) ->
	?MSG_FORMAT_FURNACE_SC_EQUIP_STATES;
packet_format(?MSG_ID_FURNACE_CS_SAVE_IMAGE) ->
	?MSG_FORMAT_FURNACE_CS_SAVE_IMAGE;
packet_format(?MSG_ID_FURNACE_COMPOSE_STONE) ->
	?MSG_FORMAT_FURNACE_COMPOSE_STONE;
packet_format(?MSG_ID_FURNACE_ADD_STONE) ->
	?MSG_FORMAT_FURNACE_ADD_STONE;
packet_format(?MSG_ID_FURNACE_SUB_STONE) ->
	?MSG_FORMAT_FURNACE_SUB_STONE;
packet_format(?MSG_ID_FURNACE_ADD_HOLE) ->
	?MSG_FORMAT_FURNACE_ADD_HOLE;
packet_format(?MSG_ID_FURNACE_CHANGE_STONE) ->
	?MSG_FORMAT_FURNACE_CHANGE_STONE;
packet_format(?MSG_ID_FURNACE_REQUEST_UP_STONE) ->
	?MSG_FORMAT_FURNACE_REQUEST_UP_STONE;
packet_format(?MSG_ID_FURNACE_CS_OK_COM_STONE_QUERY) ->
	?MSG_FORMAT_FURNACE_CS_OK_COM_STONE_QUERY;
packet_format(?MSG_ID_FURNACE_SC_OK_COM_STONE_QUERY) ->
	?MSG_FORMAT_FURNACE_SC_OK_COM_STONE_QUERY;
packet_format(?MSG_ID_FURNACE_SC_OK_COM_STONE) ->
	?MSG_FORMAT_FURNACE_SC_OK_COM_STONE;
packet_format(?MSG_ID_FURNACE_SC_COMPOSE_STONE) ->
	?MSG_FORMAT_FURNACE_SC_COMPOSE_STONE;
packet_format(?MSG_ID_FURNACE_SC_ADD_STONE) ->
	?MSG_FORMAT_FURNACE_SC_ADD_STONE;
packet_format(?MSG_ID_FURNACE_SC_SUB_STONE) ->
	?MSG_FORMAT_FURNACE_SC_SUB_STONE;
packet_format(?MSG_ID_FURNACE_SC_ADD_HOLE) ->
	?MSG_FORMAT_FURNACE_SC_ADD_HOLE;
packet_format(?MSG_ID_FURNACE_SC_CHANGE_STONE) ->
	?MSG_FORMAT_FURNACE_SC_CHANGE_STONE;
packet_format(?MSG_ID_FURNACE_CS_OK_TRANSFER) ->
	?MSG_FORMAT_FURNACE_CS_OK_TRANSFER;
packet_format(?MSG_ID_FURNACE_SC_OK_TRANSFER) ->
	?MSG_FORMAT_FURNACE_SC_OK_TRANSFER;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
