%% Author: php
%% Created:
%% Description: TODO: Add description to partner_packet
-module(partner_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_PARTNER_CS_INFO) ->
	?MSG_FORMAT_PARTNER_CS_INFO;
packet_format(?MSG_ID_PARTNER_SC_INFO) ->
	?MSG_FORMAT_PARTNER_SC_INFO;
packet_format(?MSG_ID_PARTNER_SC_ATTR_UPDATE) ->
	?MSG_FORMAT_PARTNER_SC_ATTR_UPDATE;
packet_format(?MSG_ID_PARTNER_CS_FREE) ->
	?MSG_FORMAT_PARTNER_CS_FREE;
packet_format(?MSG_ID_PARTNER_SC_FREE) ->
	?MSG_FORMAT_PARTNER_SC_FREE;
packet_format(?MSG_ID_PARTNER_CS_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_CS_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_SC_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_SC_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_MIND_INFO) ->
	?MSG_FORMAT_PARTNER_MIND_INFO;
packet_format(?MSG_ID_PARTNER_SC_MIND_INFO) ->
	?MSG_FORMAT_PARTNER_SC_MIND_INFO;
packet_format(?MSG_ID_PARTNER_CS_TRAIN) ->
	?MSG_FORMAT_PARTNER_CS_TRAIN;
packet_format(?MSG_ID_PARTNER_SC_TRAIN) ->
	?MSG_FORMAT_PARTNER_SC_TRAIN;
packet_format(?MSG_ID_PARTNER_CS_SAVE_TRAIN) ->
	?MSG_FORMAT_PARTNER_CS_SAVE_TRAIN;
packet_format(?MSG_ID_PARTNER_SC_SAVE_TRAIN) ->
	?MSG_FORMAT_PARTNER_SC_SAVE_TRAIN;
packet_format(?MSG_ID_PARTNER_CS_CANCEL_TAIN) ->
	?MSG_FORMAT_PARTNER_CS_CANCEL_TAIN;
packet_format(?MSG_ID_PARTNER_CS_INHERIT) ->
	?MSG_FORMAT_PARTNER_CS_INHERIT;
packet_format(?MSG_ID_PARTNER_SC_INHERIT) ->
	?MSG_FORMAT_PARTNER_SC_INHERIT;
packet_format(?MSG_ID_PARTNER_SC_SET_SKIPPER) ->
	?MSG_FORMAT_PARTNER_SC_SET_SKIPPER;
packet_format(?MSG_ID_PARTNER_CS_SET_ASSIST) ->
	?MSG_FORMAT_PARTNER_CS_SET_ASSIST;
packet_format(?MSG_ID_PARTNER_CS_REMOVE_ASSIST) ->
	?MSG_FORMAT_PARTNER_CS_REMOVE_ASSIST;
packet_format(?MSG_ID_PARTNER_ASSIST_GROUP) ->
	?MSG_FORMAT_PARTNER_ASSIST_GROUP;
packet_format(?MSG_ID_PARTNER_SC_SET_ASSIST) ->
	?MSG_FORMAT_PARTNER_SC_SET_ASSIST;
packet_format(?MSG_ID_PARTNER_SC_CHANGE_STATION) ->
	?MSG_FORMAT_PARTNER_SC_CHANGE_STATION;
packet_format(?MSG_ID_PARTNER_CS_CAMP_LIST) ->
	?MSG_FORMAT_PARTNER_CS_CAMP_LIST;
packet_format(?MSG_ID_PARTNER_SC_CAMP_LIST) ->
	?MSG_FORMAT_PARTNER_SC_CAMP_LIST;
packet_format(?MSG_ID_PARTNER_CS_GET_RECRUIT) ->
	?MSG_FORMAT_PARTNER_CS_GET_RECRUIT;
packet_format(?MSG_ID_PARTNER_SC_GET_RECRUIT) ->
	?MSG_FORMAT_PARTNER_SC_GET_RECRUIT;
packet_format(?MSG_ID_PARTNER_CS_EXT_BAG) ->
	?MSG_FORMAT_PARTNER_CS_EXT_BAG;
packet_format(?MSG_ID_PARTNER_SC_EXT_BAG) ->
	?MSG_FORMAT_PARTNER_SC_EXT_BAG;
packet_format(?MSG_ID_PARTNER_CS_PUB_FREE) ->
	?MSG_FORMAT_PARTNER_CS_PUB_FREE;
packet_format(?MSG_ID_PARTNER_SC_PUB_FREE) ->
	?MSG_FORMAT_PARTNER_SC_PUB_FREE;
packet_format(?MSG_ID_PARTNER_CS_ADD_LOOKNUM) ->
	?MSG_FORMAT_PARTNER_CS_ADD_LOOKNUM;
packet_format(?MSG_ID_PARTNER_SC_ADD_LOOKNUM) ->
	?MSG_FORMAT_PARTNER_SC_ADD_LOOKNUM;
packet_format(?MSG_ID_PARTNER_SC_OPEN_LOOKFOR) ->
	?MSG_FORMAT_PARTNER_SC_OPEN_LOOKFOR;
packet_format(?MSG_ID_PARTNER_CS_CLEAN_LOOK_CD) ->
	?MSG_FORMAT_PARTNER_CS_CLEAN_LOOK_CD;
packet_format(?MSG_ID_PARTNER_SC_CLEAN_LOOK_CD) ->
	?MSG_FORMAT_PARTNER_SC_CLEAN_LOOK_CD;
packet_format(?MSG_ID_PARTNER_CS_FAMOUS) ->
	?MSG_FORMAT_PARTNER_CS_FAMOUS;
packet_format(?MSG_ID_PARTNER_SC_FAMOUS) ->
	?MSG_FORMAT_PARTNER_SC_FAMOUS;
packet_format(?MSG_ID_PARTNER_SC_FREE_TRAIN) ->
	?MSG_FORMAT_PARTNER_SC_FREE_TRAIN;
packet_format(?MSG_ID_PARTNER_CS_CHANGE_EQUIP_ONCE) ->
	?MSG_FORMAT_PARTNER_CS_CHANGE_EQUIP_ONCE;
packet_format(?MSG_ID_PARTNER_SC_CHANGE_EQUIP_ONCE) ->
	?MSG_FORMAT_PARTNER_SC_CHANGE_EQUIP_ONCE;
packet_format(?MSG_ID_PARTNER_CS_CHANGE_MIND_ONCE) ->
	?MSG_FORMAT_PARTNER_CS_CHANGE_MIND_ONCE;
packet_format(?MSG_ID_PARTNER_CS_LOOKFOR_INFO) ->
	?MSG_FORMAT_PARTNER_CS_LOOKFOR_INFO;
packet_format(?MSG_ID_PARTNER_SC_LOOKFOR_INFO) ->
	?MSG_FORMAT_PARTNER_SC_LOOKFOR_INFO;
packet_format(?MSG_ID_PARTNER_CS_LOOKFOR) ->
	?MSG_FORMAT_PARTNER_CS_LOOKFOR;
packet_format(?MSG_ID_PARTNER_SC_LOOKFOR) ->
	?MSG_FORMAT_PARTNER_SC_LOOKFOR;
packet_format(?MSG_ID_PARTNER_CS_RECRUIT) ->
	?MSG_FORMAT_PARTNER_CS_RECRUIT;
packet_format(?MSG_ID_PARTNER_SC_RECRUIT) ->
	?MSG_FORMAT_PARTNER_SC_RECRUIT;
packet_format(?MSG_ID_PARTNER_CS_CALL_ON) ->
	?MSG_FORMAT_PARTNER_CS_CALL_ON;
packet_format(?MSG_ID_PARTNER_SC_CALL_ON) ->
	?MSG_FORMAT_PARTNER_SC_CALL_ON;
packet_format(?MSG_ID_PARTNER_CS_ASSEMBLE_INFO) ->
	?MSG_FORMAT_PARTNER_CS_ASSEMBLE_INFO;
packet_format(?MSG_ID_PARTNER_SC_ASSEMBLE_INFO) ->
	?MSG_FORMAT_PARTNER_SC_ASSEMBLE_INFO;
packet_format(?MSG_ID_PARTNER_CS_UP_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_CS_UP_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_SC_UP_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_SC_UP_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_CS_LOOKED_LIST) ->
	?MSG_FORMAT_PARTNER_CS_LOOKED_LIST;
packet_format(?MSG_ID_PARTNER_SC_LOOKED_LIST) ->
	?MSG_FORMAT_PARTNER_SC_LOOKED_LIST;
packet_format(?MSG_ID_PARTNER_CS_LOOK_NEW_LIST) ->
	?MSG_FORMAT_PARTNER_CS_LOOK_NEW_LIST;
packet_format(?MSG_ID_PARTNER_SC_LOOK_NEW_LIST) ->
	?MSG_FORMAT_PARTNER_SC_LOOK_NEW_LIST;
packet_format(?MSG_ID_PARTNER_CS_DEL_LOOK_NEW) ->
	?MSG_FORMAT_PARTNER_CS_DEL_LOOK_NEW;
packet_format(?MSG_ID_PARTNER_SC_DEL_LOOK_NEW) ->
	?MSG_FORMAT_PARTNER_SC_DEL_LOOK_NEW;
packet_format(?MSG_ID_PARTNER_CS_LOOK_NEW_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_CS_LOOK_NEW_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_SC_LOOK_NEW_ASSEMBLE) ->
	?MSG_FORMAT_PARTNER_SC_LOOK_NEW_ASSEMBLE;
packet_format(?MSG_ID_PARTNER_CS_DEL_ASS_NEW) ->
	?MSG_FORMAT_PARTNER_CS_DEL_ASS_NEW;
packet_format(?MSG_ID_PARTNER_SC_DEL_ASS_NEW) ->
	?MSG_FORMAT_PARTNER_SC_DEL_ASS_NEW;
packet_format(?MSG_ID_PARTNER_SC_LOOK_NEW_ID) ->
	?MSG_FORMAT_PARTNER_SC_LOOK_NEW_ID;
packet_format(?MSG_ID_PARTNER_CS_LOOK_NOTICE) ->
	?MSG_FORMAT_PARTNER_CS_LOOK_NOTICE;
packet_format(?MSG_ID_PARTNER_CS_REQUEST_TRAN) ->
	?MSG_FORMAT_PARTNER_CS_REQUEST_TRAN;
packet_format(?MSG_ID_PARTNER_TRAN_RESULT) ->
	?MSG_FORMAT_PARTNER_TRAN_RESULT;
packet_format(?MSG_ID_PARTNER_CS_SET_FOLLOW) ->
	?MSG_FORMAT_PARTNER_CS_SET_FOLLOW;
packet_format(?MSG_ID_PARTNER_SC_SET_FOLLOW) ->
	?MSG_FORMAT_PARTNER_SC_SET_FOLLOW;
packet_format(?MSG_ID_PARTNER_CS_ATTR) ->
	?MSG_FORMAT_PARTNER_CS_ATTR;
packet_format(?MSG_ID_PARTNER_SC_ATTR) ->
	?MSG_FORMAT_PARTNER_SC_ATTR;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
