%% Author: php
%% Created:
%% Description: TODO: Add description to guild_packet
-module(guild_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_GUILD_CS_LIST) ->
	?MSG_FORMAT_GUILD_CS_LIST;
packet_format(?MSG_ID_GUILD_SC_LIST) ->
	?MSG_FORMAT_GUILD_SC_LIST;
packet_format(?MSG_ID_GUILD_CS_DATA) ->
	?MSG_FORMAT_GUILD_CS_DATA;
packet_format(?MSG_ID_GUILD_SC_DATA) ->
	?MSG_FORMAT_GUILD_SC_DATA;
packet_format(?MSG_ID_GUILD_CS_MEMBER) ->
	?MSG_FORMAT_GUILD_CS_MEMBER;
packet_format(?MSG_ID_GUILD_SC_MEMBER) ->
	?MSG_FORMAT_GUILD_SC_MEMBER;
packet_format(?MSG_ID_GUILD_CS_APPLY_LIST) ->
	?MSG_FORMAT_GUILD_CS_APPLY_LIST;
packet_format(?MSG_ID_GUILD_SC_APPLY_LIST) ->
	?MSG_FORMAT_GUILD_SC_APPLY_LIST;
packet_format(?MSG_ID_GUILD_CS_CREATE) ->
	?MSG_FORMAT_GUILD_CS_CREATE;
packet_format(?MSG_ID_GUILD_SC_CREATE) ->
	?MSG_FORMAT_GUILD_SC_CREATE;
packet_format(?MSG_ID_GUILD_DISBAND) ->
	?MSG_FORMAT_GUILD_DISBAND;
packet_format(?MSG_ID_GUILD_QUIT) ->
	?MSG_FORMAT_GUILD_QUIT;
packet_format(?MSG_ID_GUILD_CS_CD) ->
	?MSG_FORMAT_GUILD_CS_CD;
packet_format(?MSG_ID_GUILD_CS_CLEAN_CD) ->
	?MSG_FORMAT_GUILD_CS_CLEAN_CD;
packet_format(?MSG_ID_GUILD_SC_CD) ->
	?MSG_FORMAT_GUILD_SC_CD;
packet_format(?MSG_ID_GUILD_CS_APPLY) ->
	?MSG_FORMAT_GUILD_CS_APPLY;
packet_format(?MSG_ID_GUILD_CS_CANCEL_APPLY) ->
	?MSG_FORMAT_GUILD_CS_CANCEL_APPLY;
packet_format(?MSG_ID_GUILD_SC_APPLY) ->
	?MSG_FORMAT_GUILD_SC_APPLY;
packet_format(?MSG_ID_GUILD_CS_DEAL_APPLY) ->
	?MSG_FORMAT_GUILD_CS_DEAL_APPLY;
packet_format(?MSG_ID_GUILD_CS_INVITE) ->
	?MSG_FORMAT_GUILD_CS_INVITE;
packet_format(?MSG_ID_GUILD_SC_INVITE) ->
	?MSG_FORMAT_GUILD_SC_INVITE;
packet_format(?MSG_ID_GUILD_CS_DEAL_INVITE) ->
	?MSG_FORMAT_GUILD_CS_DEAL_INVITE;
packet_format(?MSG_ID_GUILD_CS_DONATE) ->
	?MSG_FORMAT_GUILD_CS_DONATE;
packet_format(?MSG_ID_GUILD_CS_SKILL_DONATE) ->
	?MSG_FORMAT_GUILD_CS_SKILL_DONATE;
packet_format(?MSG_ID_GUILD_CS_SKILL_LIST) ->
	?MSG_FORMAT_GUILD_CS_SKILL_LIST;
packet_format(?MSG_ID_GUILD_SC_SKILL_LIST) ->
	?MSG_FORMAT_GUILD_SC_SKILL_LIST;
packet_format(?MSG_ID_GUILD_CS_SKILL_LEARN) ->
	?MSG_FORMAT_GUILD_CS_SKILL_LEARN;
packet_format(?MSG_ID_GUILD_SC_SKILL_LEARN) ->
	?MSG_FORMAT_GUILD_SC_SKILL_LEARN;
packet_format(?MSG_ID_GUILD_CS_MAGIC_LEARN) ->
	?MSG_FORMAT_GUILD_CS_MAGIC_LEARN;
packet_format(?MSG_ID_GUILD_SC_MAGIC_LEARN) ->
	?MSG_FORMAT_GUILD_SC_MAGIC_LEARN;
packet_format(?MSG_ID_GUILD_CS_MAGIC_LIST) ->
	?MSG_FORMAT_GUILD_CS_MAGIC_LIST;
packet_format(?MSG_ID_GUILD_SC_MAGIC_LIST) ->
	?MSG_FORMAT_GUILD_SC_MAGIC_LIST;
packet_format(?MSG_ID_GUILD_CS_TREASURE) ->
	?MSG_FORMAT_GUILD_CS_TREASURE;
packet_format(?MSG_ID_GUILD_SC_TREASURE) ->
	?MSG_FORMAT_GUILD_SC_TREASURE;
packet_format(?MSG_ID_GUILD_CS_BUY_TREASURE) ->
	?MSG_FORMAT_GUILD_CS_BUY_TREASURE;
packet_format(?MSG_ID_GUILD_CS_KICK_OUT) ->
	?MSG_FORMAT_GUILD_CS_KICK_OUT;
packet_format(?MSG_ID_GUILD_CS_CHIEF) ->
	?MSG_FORMAT_GUILD_CS_CHIEF;
packet_format(?MSG_ID_GUILD_CS_REMOVE_POS) ->
	?MSG_FORMAT_GUILD_CS_REMOVE_POS;
packet_format(?MSG_ID_GUILD_CS_IMPEACH_CHIEF) ->
	?MSG_FORMAT_GUILD_CS_IMPEACH_CHIEF;
packet_format(?MSG_ID_GUILD_CS_PROMOTE_POS) ->
	?MSG_FORMAT_GUILD_CS_PROMOTE_POS;
packet_format(?MSG_ID_GUILD_CS_INTRODUCE) ->
	?MSG_FORMAT_GUILD_CS_INTRODUCE;
packet_format(?MSG_ID_GUILD_CS_ANNOUNCE) ->
	?MSG_FORMAT_GUILD_CS_ANNOUNCE;
packet_format(?MSG_ID_GUILD_SC_ANNOUNCE) ->
	?MSG_FORMAT_GUILD_SC_ANNOUNCE;
packet_format(?MSG_ID_GUILD_CS_LOG) ->
	?MSG_FORMAT_GUILD_CS_LOG;
packet_format(?MSG_ID_GUILD_SC_LOG) ->
	?MSG_FORMAT_GUILD_SC_LOG;
packet_format(?MSG_ID_GUILD_CTN_REQUEST) ->
	?MSG_FORMAT_GUILD_CTN_REQUEST;
packet_format(?MSG_ID_GUILD_DISTRIBUTE) ->
	?MSG_FORMAT_GUILD_DISTRIBUTE;
packet_format(?MSG_ID_GUILD_SC_DISTRIBUTE) ->
	?MSG_FORMAT_GUILD_SC_DISTRIBUTE;
packet_format(?MSG_ID_GUILD_MEMBER_INFO) ->
	?MSG_FORMAT_GUILD_MEMBER_INFO;
packet_format(?MSG_ID_GUILD_SC_MEMBER_INFO) ->
	?MSG_FORMAT_GUILD_SC_MEMBER_INFO;
packet_format(?MSG_ID_GUILD_CS_MEMBER_NAME) ->
	?MSG_FORMAT_GUILD_CS_MEMBER_NAME;
packet_format(?MSG_ID_GUILD_SC_MEMBER_NAME) ->
	?MSG_FORMAT_GUILD_SC_MEMBER_NAME;
packet_format(?MSG_ID_GUILD_SC_ON_OFF) ->
	?MSG_FORMAT_GUILD_SC_ON_OFF;
packet_format(?MSG_ID_GUILD_CS_CD_LEAVE_TIME) ->
	?MSG_FORMAT_GUILD_CS_CD_LEAVE_TIME;
packet_format(?MSG_ID_GUILD_SC_CD_LEAVE_TIME) ->
	?MSG_FORMAT_GUILD_SC_CD_LEAVE_TIME;
packet_format(?MSG_ID_GUILD_CS_MEM_DETAIL) ->
	?MSG_FORMAT_GUILD_CS_MEM_DETAIL;
packet_format(?MSG_ID_GUILD_SC_MEM_DETAIL) ->
	?MSG_FORMAT_GUILD_SC_MEM_DETAIL;
packet_format(?MSG_ID_GUILD_CS_SUP_APPLY) ->
	?MSG_FORMAT_GUILD_CS_SUP_APPLY;
packet_format(?MSG_ID_GUILD_SC_SUP_APPLY) ->
	?MSG_FORMAT_GUILD_SC_SUP_APPLY;
packet_format(?MSG_ID_GUILD_SUP_APPLY_ADD) ->
	?MSG_FORMAT_GUILD_SUP_APPLY_ADD;
packet_format(?MSG_ID_GUILD_TIMEOUT_TICK) ->
	?MSG_FORMAT_GUILD_TIMEOUT_TICK;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
