%% Author: php
%% Created:
%% Description: TODO: Add description to yunying_activity_packet
-module(yunying_activity_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_YUNYING_ACTIVITY_REQUEST_DATA) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_REQUEST_DATA;
packet_format(?MSG_ID_YUNYING_ACTIVITY_AWARD_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_AWARD_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_ONLINE_START) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_ONLINE_START;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SD_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SD_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_REQUEST_SD_DATA) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_REQUEST_SD_DATA;
packet_format(?MSG_ID_YUNYING_ACTIVITY_GET_SD_GIFT) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_GET_SD_GIFT;
packet_format(?MSG_ID_YUNYING_ACTIVITY_GET_AWARD_SUCC) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_GET_AWARD_SUCC;
packet_format(?MSG_ID_YUNYING_ACTIVITY_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_STONE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_STONE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_STONE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_STONE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_STONE_AWARD) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_STONE_AWARD;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_STONE_AWARD) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_STONE_AWARD;
packet_format(?MSG_ID_YUNYING_ACTIVITY_LOTTERY_REQUEST_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_LOTTERY_REQUEST_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_LAST_LOTTERY_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_LAST_LOTTERY_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_LOTTERY) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_LOTTERY;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_LOTTERY_RESULT) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_LOTTERY_RESULT;
packet_format(?MSG_ID_YUNYING_ACTIVITY_PARTNER_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_PARTNER_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_POINT_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_POINT_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_EXCHANGE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_EXCHANGE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_EXCHANGE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_EXCHANGE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_BLESS_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_BLESS_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_BLESS_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_BLESS_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_BLESS_VALUE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_BLESS_VALUE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_BLESS_VALUE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_BLESS_VALUE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_BLESS_GET_AWARD) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_BLESS_GET_AWARD;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_BLESS_GET_AWARD) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_BLESS_GET_AWARD;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_REDBAG_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_REDBAG_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_REDBAB_NUM) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_REDBAB_NUM;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_GET_REDBAG) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_GET_REDBAG;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_REDBAG_OUTPUT) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_REDBAG_OUTPUT;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_SPRING_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_SPRING_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_GET_REDBAG) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_GET_REDBAG;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_OPEN_REDBAG) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_OPEN_REDBAG;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_STONE_VALUE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_STONE_VALUE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_STONE_VALUE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_STONE_VALUE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_STONE_VALUE_GET_AWARD) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_STONE_VALUE_GET_AWARD;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_RIDDLE_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_RIDDLE_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_RIDDLE_ANSWER) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_RIDDLE_ANSWER;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_RIDDLE_ANSWER) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_RIDDLE_ANSWER;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_RIDDLE_AWARD_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_RIDDLE_AWARD_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_RIDDLE_AWARD_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_RIDDLE_AWARD_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_TANGYUAN_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_TANGYUAN_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_CS_FREE_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_CS_FREE_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_FREE_EXCHANGE) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_FREE_EXCHANGE;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SUPER_VIP) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SUPER_VIP;
packet_format(?MSG_ID_YUNYING_ACTIVITY_SC_TIME_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_SC_TIME_INFO;
packet_format(?MSG_ID_YUNYING_ACTIVITY_TIME_INFO) ->
	?MSG_FORMAT_YUNYING_ACTIVITY_TIME_INFO;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
