%% Author: php
%% Created:
%% Description: TODO: Add description to home_packet
-module(home_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_HOME_CS_MAIN) ->
	?MSG_FORMAT_HOME_CS_MAIN;
packet_format(?MSG_ID_HOME_SC_MAIN) ->
	?MSG_FORMAT_HOME_SC_MAIN;
packet_format(?MSG_ID_HOME_SC_SLAVER_INFO) ->
	?MSG_FORMAT_HOME_SC_SLAVER_INFO;
packet_format(?MSG_ID_HOME_CS_LVUPHOME) ->
	?MSG_FORMAT_HOME_CS_LVUPHOME;
packet_format(?MSG_ID_HOME_SC_LVUPHOME) ->
	?MSG_FORMAT_HOME_SC_LVUPHOME;
packet_format(?MSG_ID_HOME_CS_DAILY_AWARD) ->
	?MSG_FORMAT_HOME_CS_DAILY_AWARD;
packet_format(?MSG_ID_HOME_SC_GET_AWARD) ->
	?MSG_FORMAT_HOME_SC_GET_AWARD;
packet_format(?MSG_ID_HOME_CS_OFFICE_TASK) ->
	?MSG_FORMAT_HOME_CS_OFFICE_TASK;
packet_format(?MSG_ID_HOME_SC_OFFICE_TASK) ->
	?MSG_FORMAT_HOME_SC_OFFICE_TASK;
packet_format(?MSG_ID_HOME_CS_REFRESH_TASK) ->
	?MSG_FORMAT_HOME_CS_REFRESH_TASK;
packet_format(?MSG_ID_HOME_SC_REFRESH_ONE_TASK) ->
	?MSG_FORMAT_HOME_SC_REFRESH_ONE_TASK;
packet_format(?MSG_ID_HOME_CS_TASK_OPERATE) ->
	?MSG_FORMAT_HOME_CS_TASK_OPERATE;
packet_format(?MSG_ID_HOME_SC_TASK_TIMES) ->
	?MSG_FORMAT_HOME_SC_TASK_TIMES;
packet_format(?MSG_ID_HOME_SC_GUIDE_INFO) ->
	?MSG_FORMAT_HOME_SC_GUIDE_INFO;
packet_format(?MSG_ID_HOME_CS_GIRL_INFO) ->
	?MSG_FORMAT_HOME_CS_GIRL_INFO;
packet_format(?MSG_ID_HOME_SC_GIRL_INFO) ->
	?MSG_FORMAT_HOME_SC_GIRL_INFO;
packet_format(?MSG_ID_HOME_CS_START_BATTLE) ->
	?MSG_FORMAT_HOME_CS_START_BATTLE;
packet_format(?MSG_ID_HOME_SC_GIRL_INFO1) ->
	?MSG_FORMAT_HOME_SC_GIRL_INFO1;
packet_format(?MSG_ID_HOME_CS_RESCUE_BATTLE) ->
	?MSG_FORMAT_HOME_CS_RESCUE_BATTLE;
packet_format(?MSG_ID_HOME_CS_RECURIT_INFO) ->
	?MSG_FORMAT_HOME_CS_RECURIT_INFO;
packet_format(?MSG_ID_HOME_SC_RECURIT_INFO) ->
	?MSG_FORMAT_HOME_SC_RECURIT_INFO;
packet_format(?MSG_ID_HOME_CS_RECUIT_GIRL) ->
	?MSG_FORMAT_HOME_CS_RECUIT_GIRL;
packet_format(?MSG_ID_HOME_SC_RECURIT_GIRL) ->
	?MSG_FORMAT_HOME_SC_RECURIT_GIRL;
packet_format(?MSG_ID_HOME_CS_LOOSEN) ->
	?MSG_FORMAT_HOME_CS_LOOSEN;
packet_format(?MSG_ID_HOME_SC_LOOSEN) ->
	?MSG_FORMAT_HOME_SC_LOOSEN;
packet_format(?MSG_ID_HOME_CS_ADD_TIMES) ->
	?MSG_FORMAT_HOME_CS_ADD_TIMES;
packet_format(?MSG_ID_HOME_SC_LOOSEN_STATE) ->
	?MSG_FORMAT_HOME_SC_LOOSEN_STATE;
packet_format(?MSG_ID_HOME_CS_BLACK_GIRL_PLAY) ->
	?MSG_FORMAT_HOME_CS_BLACK_GIRL_PLAY;
packet_format(?MSG_ID_HOME_SC_GIRL_PLAY) ->
	?MSG_FORMAT_HOME_SC_GIRL_PLAY;
packet_format(?MSG_ID_HOME_CS_HOMEMAIN_GIRL_PLAY) ->
	?MSG_FORMAT_HOME_CS_HOMEMAIN_GIRL_PLAY;
packet_format(?MSG_ID_HOME_SC_HOME_FRIENDS_GIRLS) ->
	?MSG_FORMAT_HOME_SC_HOME_FRIENDS_GIRLS;
packet_format(?MSG_ID_HOME_CS_RESIST) ->
	?MSG_FORMAT_HOME_CS_RESIST;
packet_format(?MSG_ID_HOME_CS_RESCUE_LIST) ->
	?MSG_FORMAT_HOME_CS_RESCUE_LIST;
packet_format(?MSG_ID_HOME_SC_RESCUE_LIST) ->
	?MSG_FORMAT_HOME_SC_RESCUE_LIST;
packet_format(?MSG_ID_HOME_CS_INVITE_RESCUE) ->
	?MSG_FORMAT_HOME_CS_INVITE_RESCUE;
packet_format(?MSG_ID_HOME_SC_INVITE_RESCUE) ->
	?MSG_FORMAT_HOME_SC_INVITE_RESCUE;
packet_format(?MSG_ID_HOME_CS_INVITE_RESULT) ->
	?MSG_FORMAT_HOME_CS_INVITE_RESULT;
packet_format(?MSG_ID_HOME_CS_PRESS) ->
	?MSG_FORMAT_HOME_CS_PRESS;
packet_format(?MSG_ID_HOME_CS_FAWN) ->
	?MSG_FORMAT_HOME_CS_FAWN;
packet_format(?MSG_ID_HOME_MSG_SC_USER_STATE) ->
	?MSG_FORMAT_HOME_MSG_SC_USER_STATE;
packet_format(?MSG_ID_HOME_MSG_SC_MAIN_BLACK) ->
	?MSG_FORMAT_HOME_MSG_SC_MAIN_BLACK;
packet_format(?MSG_ID_HOME_SC_INTER_INFO) ->
	?MSG_FORMAT_HOME_SC_INTER_INFO;
packet_format(?MSG_ID_HOME_CS_BLACK_GIRLINFO) ->
	?MSG_FORMAT_HOME_CS_BLACK_GIRLINFO;
packet_format(?MSG_ID_HOME_SC_BLACK_GIRLINFO) ->
	?MSG_FORMAT_HOME_SC_BLACK_GIRLINFO;
packet_format(?MSG_ID_HOME_CS_SHOW_GIRL) ->
	?MSG_FORMAT_HOME_CS_SHOW_GIRL;
packet_format(?MSG_ID_HOME_CS_RELEASE_GIRL) ->
	?MSG_FORMAT_HOME_CS_RELEASE_GIRL;
packet_format(?MSG_ID_HOME_SC_RELEASE_GIRL) ->
	?MSG_FORMAT_HOME_SC_RELEASE_GIRL;
packet_format(?MSG_ID_HOME_CS_OTHERHOME) ->
	?MSG_FORMAT_HOME_CS_OTHERHOME;
packet_format(?MSG_ID_HOME_SC_OTHERHOME) ->
	?MSG_FORMAT_HOME_SC_OTHERHOME;
packet_format(?MSG_ID_HOME_CS_GROUND_INFO) ->
	?MSG_FORMAT_HOME_CS_GROUND_INFO;
packet_format(?MSG_ID_HOME_SC_GROUND_INFO) ->
	?MSG_FORMAT_HOME_SC_GROUND_INFO;
packet_format(?MSG_ID_HOME_CS_PLANT) ->
	?MSG_FORMAT_HOME_CS_PLANT;
packet_format(?MSG_ID_HOME_SC_PLANT) ->
	?MSG_FORMAT_HOME_SC_PLANT;
packet_format(?MSG_ID_HOME_CS_REFRESHPLANT) ->
	?MSG_FORMAT_HOME_CS_REFRESHPLANT;
packet_format(?MSG_ID_HOME_SC_REFRESHPLANT) ->
	?MSG_FORMAT_HOME_SC_REFRESHPLANT;
packet_format(?MSG_ID_HOME_CS_KEYREFRESH) ->
	?MSG_FORMAT_HOME_CS_KEYREFRESH;
packet_format(?MSG_ID_HOME_SC_KEYREFRESH) ->
	?MSG_FORMAT_HOME_SC_KEYREFRESH;
packet_format(?MSG_ID_HOME_CS_GROUNDLVUP) ->
	?MSG_FORMAT_HOME_CS_GROUNDLVUP;
packet_format(?MSG_ID_HOME_SC_GROUNDLVUP) ->
	?MSG_FORMAT_HOME_SC_GROUNDLVUP;
packet_format(?MSG_ID_HOME_CS_CLEARCOLD) ->
	?MSG_FORMAT_HOME_CS_CLEARCOLD;
packet_format(?MSG_ID_HOME_SC_CLEARCOLD) ->
	?MSG_FORMAT_HOME_SC_CLEARCOLD;
packet_format(?MSG_ID_HOME_CS_OPENPLANT) ->
	?MSG_FORMAT_HOME_CS_OPENPLANT;
packet_format(?MSG_ID_HOME_SC_OPENPLANT) ->
	?MSG_FORMAT_HOME_SC_OPENPLANT;
packet_format(?MSG_ID_HOME_CS_HARVEST) ->
	?MSG_FORMAT_HOME_CS_HARVEST;
packet_format(?MSG_ID_HOME_SC_HARVEST) ->
	?MSG_FORMAT_HOME_SC_HARVEST;
packet_format(?MSG_ID_HOME_CS_PLANT_REWARD) ->
	?MSG_FORMAT_HOME_CS_PLANT_REWARD;
packet_format(?MSG_ID_HOME_SC_PLANT_REWARD) ->
	?MSG_FORMAT_HOME_SC_PLANT_REWARD;
packet_format(?MSG_ID_HOME_CS_OFFICE_AWARD) ->
	?MSG_FORMAT_HOME_CS_OFFICE_AWARD;
packet_format(?MSG_ID_HOME_SC_OFFICE_AWARD) ->
	?MSG_FORMAT_HOME_SC_OFFICE_AWARD;
packet_format(?MSG_ID_HOME_CS_GETACTIVES) ->
	?MSG_FORMAT_HOME_CS_GETACTIVES;
packet_format(?MSG_ID_HOME_CS_CLEAR_MESSAGE) ->
	?MSG_FORMAT_HOME_CS_CLEAR_MESSAGE;
packet_format(?MSG_ID_HOME_SC_CLEAR_MESSAGE) ->
	?MSG_FORMAT_HOME_SC_CLEAR_MESSAGE;
packet_format(?MSG_ID_HOME_CS_DECLEAR_INFO) ->
	?MSG_FORMAT_HOME_CS_DECLEAR_INFO;
packet_format(?MSG_ID_HOME_SC_DECLEAR_INFO) ->
	?MSG_FORMAT_HOME_SC_DECLEAR_INFO;
packet_format(?MSG_ID_HOME_CS_ETDIT_OWNER) ->
	?MSG_FORMAT_HOME_CS_ETDIT_OWNER;
packet_format(?MSG_ID_HOME_SC_EDIT_OWNER) ->
	?MSG_FORMAT_HOME_SC_EDIT_OWNER;
packet_format(?MSG_ID_HOME_CS_LEAVE_MESSAGE) ->
	?MSG_FORMAT_HOME_CS_LEAVE_MESSAGE;
packet_format(?MSG_ID_HOME_SC_EDIT_MESSAGE) ->
	?MSG_FORMAT_HOME_SC_EDIT_MESSAGE;
packet_format(?MSG_ID_HOME_CS_APPLY_LEAVE_MESSAGE) ->
	?MSG_FORMAT_HOME_CS_APPLY_LEAVE_MESSAGE;
packet_format(?MSG_ID_HOME_SC_LEAVE_MESSAGE) ->
	?MSG_FORMAT_HOME_SC_LEAVE_MESSAGE;
packet_format(?MSG_ID_HOME_CS_DELETE_MESSAGE) ->
	?MSG_FORMAT_HOME_CS_DELETE_MESSAGE;
packet_format(?MSG_ID_HOME_SC_DELETE_MESSAGE) ->
	?MSG_FORMAT_HOME_SC_DELETE_MESSAGE;
packet_format(?MSG_ID_HOME_CS_VISIT_RECORD) ->
	?MSG_FORMAT_HOME_CS_VISIT_RECORD;
packet_format(?MSG_ID_HOME_SC_VISIT_RECORD) ->
	?MSG_FORMAT_HOME_SC_VISIT_RECORD;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
