%% Author: php
%% Created:
%% Description: TODO: Add description to invasion_packet
-module(invasion_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_INVASION_CS_START_GUARD) ->
	?MSG_FORMAT_INVASION_CS_START_GUARD;
packet_format(?MSG_ID_INVASION_SC_START_GUARD) ->
	?MSG_FORMAT_INVASION_SC_START_GUARD;
packet_format(?MSG_ID_INVASION_CS_END) ->
	?MSG_FORMAT_INVASION_CS_END;
packet_format(?MSG_ID_INVASION_SC_END) ->
	?MSG_FORMAT_INVASION_SC_END;
packet_format(?MSG_ID_INVASION_SCDEFENDEND) ->
	?MSG_FORMAT_INVASION_SCDEFENDEND;
packet_format(?MSG_ID_INVASION_SCMONHP) ->
	?MSG_FORMAT_INVASION_SCMONHP;
packet_format(?MSG_ID_INVASION_SC_REBORN) ->
	?MSG_FORMAT_INVASION_SC_REBORN;
packet_format(?MSG_ID_INVASION_CS_START_BATTLE) ->
	?MSG_FORMAT_INVASION_CS_START_BATTLE;
packet_format(?MSG_ID_INVASION_SC_START_MONSTER) ->
	?MSG_FORMAT_INVASION_SC_START_MONSTER;
packet_format(?MSG_ID_INVASION_CS_CLEAR_REBORN_CD) ->
	?MSG_FORMAT_INVASION_CS_CLEAR_REBORN_CD;
packet_format(?MSG_ID_INVASION_CS_I_WANA_REBORN) ->
	?MSG_FORMAT_INVASION_CS_I_WANA_REBORN;
packet_format(?MSG_ID_INVASION_CSHALLINFO) ->
	?MSG_FORMAT_INVASION_CSHALLINFO;
packet_format(?MSG_ID_INVASION_SCHALLINFO) ->
	?MSG_FORMAT_INVASION_SCHALLINFO;
packet_format(?MSG_ID_INVASION_SCATTACK) ->
	?MSG_FORMAT_INVASION_SCATTACK;
packet_format(?MSG_ID_INVASION_SCATTACKOVER) ->
	?MSG_FORMAT_INVASION_SCATTACKOVER;
packet_format(?MSG_ID_INVASION_SCMONSTERINFO) ->
	?MSG_FORMAT_INVASION_SCMONSTERINFO;
packet_format(?MSG_ID_INVASION_HURT_RANK) ->
	?MSG_FORMAT_INVASION_HURT_RANK;
packet_format(?MSG_ID_INVASION_CSEVALUATION) ->
	?MSG_FORMAT_INVASION_CSEVALUATION;
packet_format(?MSG_ID_INVASION_SCEVALUATION) ->
	?MSG_FORMAT_INVASION_SCEVALUATION;
packet_format(?MSG_ID_INVASION_CSTURNCARD) ->
	?MSG_FORMAT_INVASION_CSTURNCARD;
packet_format(?MSG_ID_INVASION_SCTURNCARD) ->
	?MSG_FORMAT_INVASION_SCTURNCARD;
packet_format(?MSG_ID_INVASION_SCBATTLE) ->
	?MSG_FORMAT_INVASION_SCBATTLE;
packet_format(?MSG_ID_INVASION_MON_COLLISON) ->
	?MSG_FORMAT_INVASION_MON_COLLISON;
packet_format(?MSG_ID_INVASION_MON_START_BATTLE) ->
	?MSG_FORMAT_INVASION_MON_START_BATTLE;
packet_format(?MSG_ID_INVASION_DOLL_REWARD) ->
	?MSG_FORMAT_INVASION_DOLL_REWARD;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
