%% Author: php
%% Created:
%% Description: TODO: Add description to single_arena_packet
-module(single_arena_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_SINGLE_ARENA_CS_ENTER) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_ENTER;
packet_format(?MSG_ID_SINGLE_ARENA_SC_ENTER) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_ENTER;
packet_format(?MSG_ID_SINGLE_ARENA_CS_CLEAR_CD) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_CLEAR_CD;
packet_format(?MSG_ID_SINGLE_ARENA_SC_CLEAR_CD) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_CLEAR_CD;
packet_format(?MSG_ID_SINGLE_ARENA_CS_START_BATTLE) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_START_BATTLE;
packet_format(?MSG_ID_SINGLE_ARENA_CS_WIN_STREAK_AWARD) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_WIN_STREAK_AWARD;
packet_format(?MSG_ID_SINGLE_ARENA_SC_WIN_STREAK_AWARD) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_WIN_STREAK_AWARD;
packet_format(?MSG_ID_SINGLE_ARENA_CS_RANK) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_RANK;
packet_format(?MSG_ID_SINGLE_ARENA_SC_RANK) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_RANK;
packet_format(?MSG_ID_SINGLE_ARENA_CS_BUY_CHALLENGE_TIME) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_BUY_CHALLENGE_TIME;
packet_format(?MSG_ID_SINGLE_ARENA_SC_BUY_CHALLENGE_TIME) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_BUY_CHALLENGE_TIME;
packet_format(?MSG_ID_SINGLE_ARENA_CS_RANK_AWARD) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_RANK_AWARD;
packet_format(?MSG_ID_SINGLE_ARENA_SC_RANK_AWARD) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_RANK_AWARD;
packet_format(?MSG_ID_SINGLE_ARENA_CS_GET_REPORT) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_GET_REPORT;
packet_format(?MSG_ID_SINGLE_ARENA_SC_REFRESH_PER_REPORT) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_REFRESH_PER_REPORT;
packet_format(?MSG_ID_SINGLE_ARENA_CS_CHAMPION_REPORT) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_CHAMPION_REPORT;
packet_format(?MSG_ID_SINGLE_ARENA_SC_CHAMPION_REPORT) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_CHAMPION_REPORT;
packet_format(?MSG_ID_SINGLE_ARENA_CS_TOP_RANK) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_TOP_RANK;
packet_format(?MSG_ID_SINGLE_ARENA_SC_TOP_RANK) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_TOP_RANK;
packet_format(?MSG_ID_SINGLE_ARENA_CS_TOP_STREAK) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_TOP_STREAK;
packet_format(?MSG_ID_SINGLE_ARENA_SC_TOP_STREAK) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_TOP_STREAK;
packet_format(?MSG_ID_SINGLE_ARENA_SC_REFRESH_CHALLENGE_LIST) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_REFRESH_CHALLENGE_LIST;
packet_format(?MSG_ID_SINGLE_ARENA_SC_REFRESH_REPORT) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_REFRESH_REPORT;
packet_format(?MSG_ID_SINGLE_ARENA_CS_LOGIN_DATA) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_LOGIN_DATA;
packet_format(?MSG_ID_SINGLE_ARENA_SC_LOGIN_DATA) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_LOGIN_DATA;
packet_format(?MSG_ID_SINGLE_ARENA_CS_EXCHANGE) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_EXCHANGE;
packet_format(?MSG_ID_SINGLE_ARENA_SC_SCORE_UPDATE) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_SCORE_UPDATE;
packet_format(?MSG_ID_SINGLE_ARENA_SC_TARGET) ->
	?MSG_FORMAT_SINGLE_ARENA_SC_TARGET;
packet_format(?MSG_ID_SINGLE_ARENA_CS_GET_TARGET_REWARD) ->
	?MSG_FORMAT_SINGLE_ARENA_CS_GET_TARGET_REWARD;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
