%% Author: php
%% Created:
%% Description: TODO: Add description to guild_pvp_packet
-module(guild_pvp_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_GUILD_PVP_CS_ENTER) ->
	?MSG_FORMAT_GUILD_PVP_CS_ENTER;
packet_format(?MSG_ID_GUILD_PVP_CS_BATTLE) ->
	?MSG_FORMAT_GUILD_PVP_CS_BATTLE;
packet_format(?MSG_ID_GUILD_PVP_CS_EXIT) ->
	?MSG_FORMAT_GUILD_PVP_CS_EXIT;
packet_format(?MSG_ID_GUILD_PVP_CS_CHANGE_STATE) ->
	?MSG_FORMAT_GUILD_PVP_CS_CHANGE_STATE;
packet_format(?MSG_ID_GUILD_PVP_CS_INIT_MAP_OK) ->
	?MSG_FORMAT_GUILD_PVP_CS_INIT_MAP_OK;
packet_format(?MSG_ID_GUILD_PVP_CS_ENCOURAGE) ->
	?MSG_FORMAT_GUILD_PVP_CS_ENCOURAGE;
packet_format(?MSG_ID_GUILD_PVP_CS_APP) ->
	?MSG_FORMAT_GUILD_PVP_CS_APP;
packet_format(?MSG_ID_GUILD_PVP_CS_GET_APP_INFO) ->
	?MSG_FORMAT_GUILD_PVP_CS_GET_APP_INFO;
packet_format(?MSG_ID_GUILD_PVP_CS_ADD_DEF_GUILD) ->
	?MSG_FORMAT_GUILD_PVP_CS_ADD_DEF_GUILD;
packet_format(?MSG_ID_GUILD_PVP_CS_CAR_FIRE) ->
	?MSG_FORMAT_GUILD_PVP_CS_CAR_FIRE;
packet_format(?MSG_ID_GUILD_PVP_CS_FIX_WALL) ->
	?MSG_FORMAT_GUILD_PVP_CS_FIX_WALL;
packet_format(?MSG_ID_GUILD_PVP_CS_BRING_BACK) ->
	?MSG_FORMAT_GUILD_PVP_CS_BRING_BACK;
packet_format(?MSG_ID_GUILD_PVP_CS_GUILD_WALL_INFO) ->
	?MSG_FORMAT_GUILD_PVP_CS_GUILD_WALL_INFO;
packet_format(?MSG_ID_GUILD_PVP_CS_WALL_LIST) ->
	?MSG_FORMAT_GUILD_PVP_CS_WALL_LIST;
packet_format(?MSG_ID_GUILD_PVP_CS_ATT_WALL) ->
	?MSG_FORMAT_GUILD_PVP_CS_ATT_WALL;
packet_format(?MSG_ID_GUILD_PVP_CS_GIVEUP_WALL) ->
	?MSG_FORMAT_GUILD_PVP_CS_GIVEUP_WALL;
packet_format(?MSG_ID_GUILD_PVP_CS_APP_LIST) ->
	?MSG_FORMAT_GUILD_PVP_CS_APP_LIST;
packet_format(?MSG_ID_GUILD_PVP_ENTER_INFO) ->
	?MSG_FORMAT_GUILD_PVP_ENTER_INFO;
packet_format(?MSG_ID_GUILD_PVP_TOWER_OWNER_INFO) ->
	?MSG_FORMAT_GUILD_PVP_TOWER_OWNER_INFO;
packet_format(?MSG_ID_GUILD_PVP_GUILD_UP_ATT_WALL) ->
	?MSG_FORMAT_GUILD_PVP_GUILD_UP_ATT_WALL;
packet_format(?MSG_ID_GUILD_PVP_REQUEST_BUG_GUILD_ITEMS) ->
	?MSG_FORMAT_GUILD_PVP_REQUEST_BUG_GUILD_ITEMS;
packet_format(?MSG_ID_GUILD_PVP_CS_GUILD_MEMBER_LIST) ->
	?MSG_FORMAT_GUILD_PVP_CS_GUILD_MEMBER_LIST;
packet_format(?MSG_ID_GUILD_PVP_BROAD_RANK) ->
	?MSG_FORMAT_GUILD_PVP_BROAD_RANK;
packet_format(?MSG_ID_GUILD_PVP_SC_ENCOURAGE) ->
	?MSG_FORMAT_GUILD_PVP_SC_ENCOURAGE;
packet_format(?MSG_ID_GUILD_PVP_SC_STATE_CHANGE) ->
	?MSG_FORMAT_GUILD_PVP_SC_STATE_CHANGE;
packet_format(?MSG_ID_GUILD_PVP_MONSTER_HP) ->
	?MSG_FORMAT_GUILD_PVP_MONSTER_HP;
packet_format(?MSG_ID_GUILD_PVP_MONSTER_DEAD) ->
	?MSG_FORMAT_GUILD_PVP_MONSTER_DEAD;
packet_format(?MSG_ID_GUILD_PVP_BROAD_END) ->
	?MSG_FORMAT_GUILD_PVP_BROAD_END;
packet_format(?MSG_ID_GUILD_PVP_APP_INFO) ->
	?MSG_FORMAT_GUILD_PVP_APP_INFO;
packet_format(?MSG_ID_GUILD_PVP_APP_LIST) ->
	?MSG_FORMAT_GUILD_PVP_APP_LIST;
packet_format(?MSG_ID_GUILD_PVP_SC_ENTER_INFO) ->
	?MSG_FORMAT_GUILD_PVP_SC_ENTER_INFO;
packet_format(?MSG_ID_GUILD_PVP_SC_TOWER_OWNER_INFO) ->
	?MSG_FORMAT_GUILD_PVP_SC_TOWER_OWNER_INFO;
packet_format(?MSG_ID_GUILD_PVP_SC_ATT_WALL_LIST) ->
	?MSG_FORMAT_GUILD_PVP_SC_ATT_WALL_LIST;
packet_format(?MSG_ID_GUILD_PVP_BOSS_STATE) ->
	?MSG_FORMAT_GUILD_PVP_BOSS_STATE;
packet_format(?MSG_ID_GUILD_PVP_ENTER_SUCCESS) ->
	?MSG_FORMAT_GUILD_PVP_ENTER_SUCCESS;
packet_format(?MSG_ID_GUILD_PVP_TIME_SYC) ->
	?MSG_FORMAT_GUILD_PVP_TIME_SYC;
packet_format(?MSG_ID_GUILD_PVP_MONSTER_INFO) ->
	?MSG_FORMAT_GUILD_PVP_MONSTER_INFO;
packet_format(?MSG_ID_GUILD_PVP_MSG_ID_GUILD_PVP_ENTER_CD) ->
	?MSG_FORMAT_GUILD_PVP_MSG_ID_GUILD_PVP_ENTER_CD;
packet_format(?MSG_ID_GUILD_PVP_SKILL_CD) ->
	?MSG_FORMAT_GUILD_PVP_SKILL_CD;
packet_format(?MSG_ID_GUILD_PVP_ANNOUNMENT) ->
	?MSG_FORMAT_GUILD_PVP_ANNOUNMENT;
packet_format(?MSG_ID_GUILD_PVP_BRING_BACK_RESULT) ->
	?MSG_FORMAT_GUILD_PVP_BRING_BACK_RESULT;
packet_format(?MSG_ID_GUILD_PVP_SC_ATT_WALL_INFO) ->
	?MSG_FORMAT_GUILD_PVP_SC_ATT_WALL_INFO;
packet_format(?MSG_ID_GUILD_PVP_MAP_INFO) ->
	?MSG_FORMAT_GUILD_PVP_MAP_INFO;
packet_format(?MSG_ID_GUILD_PVP_GUILD_ITEM_NOT_ENOUGH) ->
	?MSG_FORMAT_GUILD_PVP_GUILD_ITEM_NOT_ENOUGH;
packet_format(?MSG_ID_GUILD_PVP_SC_GUILD_MEMBER_LIST) ->
	?MSG_FORMAT_GUILD_PVP_SC_GUILD_MEMBER_LIST;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
