%% Author: php
%% Created:
%% Description: TODO: Add description to player_packet
-module(player_packet).

%%
%% Include files
%%
-include("../include/const.common.hrl").
-include("../include/const.protocol.hrl").
%%
%% Exported Functions
%%
-export([packet_format/1]).
%%
%% API Functions
%%
%% *必须实现方法
%% 消息号与消息格式一一对应
packet_format(?MSG_ID_PLAYER_LOGIN_REQUEST) ->
	?MSG_FORMAT_PLAYER_LOGIN_REQUEST;
packet_format(?MSG_ID_PLAYER_LOGIN_OK) ->
	?MSG_FORMAT_PLAYER_LOGIN_OK;
packet_format(?MSG_ID_PLAYER_LOGIN_DEBUG) ->
	?MSG_FORMAT_PLAYER_LOGIN_DEBUG;
packet_format(?MSG_ID_PLAYER_LOGIN_ERROR) ->
	?MSG_FORMAT_PLAYER_LOGIN_ERROR;
packet_format(?MSG_ID_PLAYER_CREAT_REQUEST) ->
	?MSG_FORMAT_PLAYER_CREAT_REQUEST;
packet_format(?MSG_ID_PLAYER_CREAT_OK) ->
	?MSG_FORMAT_PLAYER_CREAT_OK;
packet_format(?MSG_ID_PLAYER_CS_REQ_LOGIN_INFO) ->
	?MSG_FORMAT_PLAYER_CS_REQ_LOGIN_INFO;
packet_format(?MSG_ID_PLAYER_CREAT_ERROR) ->
	?MSG_FORMAT_PLAYER_CREAT_ERROR;
packet_format(?MSG_ID_PLAYER_CS_LOGIN_GUEST) ->
	?MSG_FORMAT_PLAYER_CS_LOGIN_GUEST;
packet_format(?MSG_ID_PLAYER_DATA_REQUEST) ->
	?MSG_FORMAT_PLAYER_DATA_REQUEST;
packet_format(?MSG_ID_PLAYER_DATA_INFO) ->
	?MSG_FORMAT_PLAYER_DATA_INFO;
packet_format(?MSG_ID_PLAYER_SC_AB) ->
	?MSG_FORMAT_PLAYER_SC_AB;
packet_format(?MSG_ID_PLAYER_ATTR_UPDATE) ->
	?MSG_FORMAT_PLAYER_ATTR_UPDATE;
packet_format(?MSG_ID_PLAYER_ATTR_UPDATE_STR) ->
	?MSG_FORMAT_PLAYER_ATTR_UPDATE_STR;
packet_format(?MSG_ID_PLAYER_SC_UPDATE_MONEY) ->
	?MSG_FORMAT_PLAYER_SC_UPDATE_MONEY;
packet_format(?MSG_ID_PLAYER_SC_VIP_INFO) ->
	?MSG_FORMAT_PLAYER_SC_VIP_INFO;
packet_format(?MSG_ID_PLAYER_CS_POSITION_INFO) ->
	?MSG_FORMAT_PLAYER_CS_POSITION_INFO;
packet_format(?MSG_ID_PLAYER_CS_UPGRADE) ->
	?MSG_FORMAT_PLAYER_CS_UPGRADE;
packet_format(?MSG_ID_PLAYER_SC_UPGRADE) ->
	?MSG_FORMAT_PLAYER_SC_UPGRADE;
packet_format(?MSG_ID_PLAYER_CS_SALARY) ->
	?MSG_FORMAT_PLAYER_CS_SALARY;
packet_format(?MSG_ID_PLAYER_SC_POSITION_INFO) ->
	?MSG_FORMAT_PLAYER_SC_POSITION_INFO;
packet_format(?MSG_ID_PLAYER_CS_BUFF_INFO) ->
	?MSG_FORMAT_PLAYER_CS_BUFF_INFO;
packet_format(?MSG_ID_PLAYER_SC_BUFF_INFO) ->
	?MSG_FORMAT_PLAYER_SC_BUFF_INFO;
packet_format(?MSG_ID_PLAYER_SC_BUFF_INSERT) ->
	?MSG_FORMAT_PLAYER_SC_BUFF_INSERT;
packet_format(?MSG_ID_PLAYER_SC_BUFF_DELETE) ->
	?MSG_FORMAT_PLAYER_SC_BUFF_DELETE;
packet_format(?MSG_ID_PLAYER_CS_BUY_SP) ->
	?MSG_FORMAT_PLAYER_CS_BUY_SP;
packet_format(?MSG_ID_PLAYER_SC_BUY_SP_INFO) ->
	?MSG_FORMAT_PLAYER_SC_BUY_SP_INFO;
packet_format(?MSG_ID_PLAYER_CS_SP_BUY_TIMES) ->
	?MSG_FORMAT_PLAYER_CS_SP_BUY_TIMES;
packet_format(?MSG_ID_PLAYER_CS_RECONNECT) ->
	?MSG_FORMAT_PLAYER_CS_RECONNECT;
packet_format(?MSG_ID_PLAYER_SC_RECONNECT_SUCCESS) ->
	?MSG_FORMAT_PLAYER_SC_RECONNECT_SUCCESS;
packet_format(?MSG_ID_PLAYER_SC_RECONNECT_FAIL) ->
	?MSG_FORMAT_PLAYER_SC_RECONNECT_FAIL;
packet_format(?MSG_ID_PLAYER_SC_GIFT_CASH) ->
	?MSG_FORMAT_PLAYER_SC_GIFT_CASH;
packet_format(?MSG_ID_PLAYER_CS_GET_GIFT_CASH) ->
	?MSG_FORMAT_PLAYER_CS_GET_GIFT_CASH;
packet_format(?MSG_ID_PLAYER_CS_GET_GIFT) ->
	?MSG_FORMAT_PLAYER_CS_GET_GIFT;
packet_format(?MSG_ID_PLAYER_SC_GET_GIFT_INFO) ->
	?MSG_FORMAT_PLAYER_SC_GET_GIFT_INFO;
packet_format(?MSG_ID_PLAYER_SC_OLD_SERVER_USER) ->
	?MSG_FORMAT_PLAYER_SC_OLD_SERVER_USER;
packet_format(?MSG_ID_PLAYER_SC_FCM_NOTICE) ->
	?MSG_FORMAT_PLAYER_SC_FCM_NOTICE;
packet_format(?MSG_ID_PLAYER_CS_FCM_SUBMIT_INFO) ->
	?MSG_FORMAT_PLAYER_CS_FCM_SUBMIT_INFO;
packet_format(?MSG_ID_PLAYER_SC_FCM_SUBMIT_INFO) ->
	?MSG_FORMAT_PLAYER_SC_FCM_SUBMIT_INFO;
packet_format(?MSG_ID_PLAYER_CS_HIDE_SKIN) ->
	?MSG_FORMAT_PLAYER_CS_HIDE_SKIN;
packet_format(?MSG_ID_PLAYER_SC_HIDE_SKIN_INFO) ->
	?MSG_FORMAT_PLAYER_SC_HIDE_SKIN_INFO;
packet_format(?MSG_ID_PLAYER_SC_FCM_OFFLINE_NOTICE) ->
	?MSG_FORMAT_PLAYER_SC_FCM_OFFLINE_NOTICE;
packet_format(?MSG_ID_PLAYER_CS_OPEN_SYS_INFO) ->
	?MSG_FORMAT_PLAYER_CS_OPEN_SYS_INFO;
packet_format(?MSG_ID_PLAYER_SC_OPEN_SYS_INFO) ->
	?MSG_FORMAT_PLAYER_SC_OPEN_SYS_INFO;
packet_format(?MSG_ID_PLAYER_SC_OPEN_SYS_NOTICE) ->
	?MSG_FORMAT_PLAYER_SC_OPEN_SYS_NOTICE;
packet_format(?MSG_ID_PLAYER_CS_UPGRATE_CULTIVATION) ->
	?MSG_FORMAT_PLAYER_CS_UPGRATE_CULTIVATION;
packet_format(?MSG_ID_PLAYER_SC_CULTI_NOW) ->
	?MSG_FORMAT_PLAYER_SC_CULTI_NOW;
packet_format(?MSG_ID_PLAYER_CS_GET_GIFT_VIP) ->
	?MSG_FORMAT_PLAYER_CS_GET_GIFT_VIP;
packet_format(?MSG_ID_PLAYER_SC_GIFT_VIP_INFO) ->
	?MSG_FORMAT_PLAYER_SC_GIFT_VIP_INFO;
packet_format(?MSG_ID_PLAYER_CS_GET_DAILY_VIP) ->
	?MSG_FORMAT_PLAYER_CS_GET_DAILY_VIP;
packet_format(?MSG_ID_PLAYER_SC_VIP_DAILY_INFO) ->
	?MSG_FORMAT_PLAYER_SC_VIP_DAILY_INFO;
packet_format(?MSG_ID_PLAYER_CS_OPEN_CULTI) ->
	?MSG_FORMAT_PLAYER_CS_OPEN_CULTI;
packet_format(?MSG_ID_PLAYER_SC_OPEN_CULTI) ->
	?MSG_FORMAT_PLAYER_SC_OPEN_CULTI;
packet_format(?MSG_ID_PLAYER_CLICK) ->
	?MSG_FORMAT_PLAYER_CLICK;
packet_format(?MSG_ID_PLAYER_CS_SEND_TO_GM) ->
	?MSG_FORMAT_PLAYER_CS_SEND_TO_GM;
packet_format(?MSG_ID_PLAYER_SC_GM_RETURN) ->
	?MSG_FORMAT_PLAYER_SC_GM_RETURN;
packet_format(?MSG_ID_PLAYER_CS_STAT) ->
	?MSG_FORMAT_PLAYER_CS_STAT;
packet_format(?MSG_ID_PLAYER_SC_ILLEGAL_NOTICE) ->
	?MSG_FORMAT_PLAYER_SC_ILLEGAL_NOTICE;
packet_format(?MSG_ID_PLAYER_SC_NOT_ENOUGH_SP) ->
	?MSG_FORMAT_PLAYER_SC_NOT_ENOUGH_SP;
packet_format(?MSG_ID_PLAYER_CS_CHANGE_NAME) ->
	?MSG_FORMAT_PLAYER_CS_CHANGE_NAME;
packet_format(?MSG_ID_PLAYER_IS_OK) ->
	?MSG_FORMAT_PLAYER_IS_OK;
packet_format(?MSG_ID_PLAYER_SC_CHANGE_NAME_FLAGS) ->
	?MSG_FORMAT_PLAYER_SC_CHANGE_NAME_FLAGS;
packet_format(?MSG_ID_PLAYER_CS_ENTER_NEWBIE) ->
	?MSG_FORMAT_PLAYER_CS_ENTER_NEWBIE;
packet_format(?MSG_ID_PLAYER_SC_NEWBIE_STEP) ->
	?MSG_FORMAT_PLAYER_SC_NEWBIE_STEP;
packet_format(?MSG_ID_PLAYER_CS_ARENA_RANK) ->
	?MSG_FORMAT_PLAYER_CS_ARENA_RANK;
packet_format(?MSG_ID_PLAYER_SC_ARENA_RANK) ->
	?MSG_FORMAT_PLAYER_SC_ARENA_RANK;
packet_format(?MSG_ID_PLAYER_SC_WORLD_LV) ->
	?MSG_FORMAT_PLAYER_SC_WORLD_LV;
packet_format(?MSG_ID_PLAYER_SC_TEST_SERVER) ->
	?MSG_FORMAT_PLAYER_SC_TEST_SERVER;
packet_format(?MSG_ID_PLAYER_CS_CHANGE_PRO) ->
	?MSG_FORMAT_PLAYER_CS_CHANGE_PRO;
packet_format(?MSG_ID_PLAYER_MOVE_SERVER) ->
	?MSG_FORMAT_PLAYER_MOVE_SERVER;
packet_format(?MSG_ID_PLAYER_MOVE_SERVER_SUCCESS) ->
	?MSG_FORMAT_PLAYER_MOVE_SERVER_SUCCESS;
packet_format(?MSG_ID_PLAYER_CS_TEST_SERVER_INFO) ->
	?MSG_FORMAT_PLAYER_CS_TEST_SERVER_INFO;
packet_format(?MSG_ID_PLAYER_SC_TEST_SERVER_INFO) ->
	?MSG_FORMAT_PLAYER_SC_TEST_SERVER_INFO;
packet_format(?MSG_ID_PLAYER_CS_GET_TEST_SERVER_AWARD) ->
	?MSG_FORMAT_PLAYER_CS_GET_TEST_SERVER_AWARD;
packet_format(?MSG_ID_PLAYER_IS_CAN_GET_TEST_AWARD) ->
	?MSG_FORMAT_PLAYER_IS_CAN_GET_TEST_AWARD;
packet_format(?MSG_ID_PLAYER_CS_REQUEST_TEST_AWARD_INFO) ->
	?MSG_FORMAT_PLAYER_CS_REQUEST_TEST_AWARD_INFO;
packet_format(?MSG_ID_PLAYER_SC_TSP) ->
	?MSG_FORMAT_PLAYER_SC_TSP;
packet_format(?MSG_ID_PLAYER_HEART) ->
	?MSG_FORMAT_PLAYER_HEART;
packet_format(?MSG_ID_PLAYER_REPEAT_LOGIN) ->
	?MSG_FORMAT_PLAYER_REPEAT_LOGIN;
packet_format(MsgId) ->
	?MSG_ERROR("~p~n", [MsgId]).
%%
%% Local Functions
%%
